import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLang = new BehaviorSubject<string>('en');
  currentLang$ = this.currentLang.asObservable();

  private translations: any = {
    en: {
      'PAGE_TITLES': {
        'User Login': 'User Login',
        'Register New User': 'Register New User',
        'Admin Dashboard': 'Admin Dashboard',
        'Employee Dashboard': 'Employee Dashboard',
        'User Management': 'User Management',
        'Employee Management': 'Employee Management',
        'Supplier Management': 'Supplier Management',
        'Customer Management': 'Customer Management',
        'Change Password': 'Change Password',
        'User Profile': 'User Profile',
        'Supplier Dashboard': 'Supplier Dashboard',
        'My Supplies': 'My Supplies',
        'Order Management': 'Order Management',
        'Quotation Management': 'Quotation Management',
        'Product Category': 'Product Category',
        'Attendance Management': 'Attendance Management',
        'Loan & Advance Management': 'Loan & Advance Management',
        'Payroll Automation': 'Payroll Automation',
        'Designation Salary Settings': 'Designation Salary Settings',
        'Log Management History': 'Log Management History',
        'Add Supply Order': 'Add Supply Order',
        'Raw Material Cutting': 'Raw Material Cutting',
        'Supply Request Management': 'Supply Request Management',
        'GRN Invoice': 'GRN Invoice',
        'Receipt Dashboard': 'Receipt Dashboard',
        'Add Receipt': 'Add Receipt',
        'Printable Receipt': 'Printable Receipt',
        'Expense Management': 'Expense Management',
        'Stock Inventory': 'Stock Inventory',
        'Accounts Dashboard': 'Accounts Dashboard'
      },
      'REGISTER_USER': {
        'CREATE_TITLE': 'Create System User',
        'CREATE_SUBTITLE': 'Assign roles and credentials for new staff members',
        'BACK_TO_DIRECTORY': 'Back to Directory',
        'REGISTRATION_TYPE': 'Registration Type',
        'SYSTEM_USER': 'System User',
        'NON_SYSTEM_USER': 'Non-System User',
        'USER_ROLE': 'User Role',
        'ENTITY_TYPE': 'Entity Type',
        'ROLE_EMPLOYEE': 'Employee',
        'ROLE_SUPPLIER': 'Supplier',
        'ROLE_CUSTOMER': 'Customer',
        'AUTH_DETAILS': 'Authentication Details',
        'USERNAME': 'Username',
        'PASSWORD': 'Password',
        'CONFIRM_PASSWORD': 'Confirm Password',
        'DETAILS': 'Details',
        'FULL_NAME': 'Full Name / Entity Name',
        'MOBILE': 'Mobile Number',
        'EMAIL': 'Email Address',
        'ADDRESS': 'Address',
        'NIC': 'NIC Number',
        'DESIGNATION': 'Designation',
        'DATE_JOINED': 'Date of Joining',
        'SUPPLIER_CATEGORY': 'Supplier Category',
        'SUP_CAT_REGULAR': 'Regular (System Access Required)',
        'SUP_CAT_LOCAL': 'Local',
        'SUP_CAT_INTERNATIONAL': 'International',
        'SUP_CAT_SPECIALIZED': 'Specialized',
        'BTN_PROCESSING': 'Processing...',
        'BTN_COMPLETE': 'Complete Registration',
        'BTN_CANCEL': 'Cancel'
      },
      'USER_PROFILE': {
        'EDIT_PROFILE': 'Edit Profile',
        'USER_INFO': 'User Information',
        'USERNAME': 'Username:',
        'SYSTEM_ID': 'System ID:',
        'EMAIL': 'Email Address:',
        'PHONE': 'Phone Number:',
        'MEMBER_SINCE': 'Member Since:',
        'LAST_LOGIN': 'Last Login:',
        'BIO': 'Profile Bio / Details:',
        'NOT_PROVIDED': 'Not provided',
        'NO_BIO': 'No additional details provided.',
        'SAVE_CHANGES': 'Save Changes',
        'CANCEL': 'Cancel',
        'ACCOUNT_ACTIVE': 'Account Active',
        'ACCOUNT_INACTIVE': 'Account Inactive',
        'SECURE_MSG': 'Your account is secured with 256-bit JWT Encryption.',
        'UPDATE_SECURITY': 'Update Security',
        'SYS_PERMS': 'System Permissions',
        'PERM_DASHBOARD': 'Access Dashboard',
        'PERM_MANAGE': 'Manage Resources',
        'PERM_ADMIN': 'Administrative Controls',
        'PERM_REPORTS': 'View Reports'
      },
      'MY_SUPPLIES': {
        'TITLE': 'My Supplies',
        'SUBTITLE': 'Supply raw material orders recorded for your supplier account',
        'SEARCH_PLACEHOLDER': 'Search invoice, wood type, or date',
        'LOGIN': 'Login',
        'ROLE': 'Role',
        'EMAIL': 'Email',
        'NOT_SPECIFIED': 'Not specified',
        'TOTAL_ORDERS': 'Total Orders',
        'TOTAL_MATERIAL': 'Total Material',
        'TOTAL_NET_AMOUNT': 'Total Net Amount',
        'LOADING': 'Loading your supply records...',
        'TH_INVOICE': 'Invoice',
        'TH_DATE': 'Date',
        'TH_WOOD_TYPE': 'Wood Type',
        'TH_TOTAL_CFT': 'Total CFT',
        'TH_NET_AMOUNT': 'Net Amount',
        'TH_GRN': 'GRN',
        'TH_ACTION': 'Action',
        'STATUS_CREATED': 'Created',
        'STATUS_PENDING': 'Pending',
        'NO_RECORDS': 'No supply records found for your account.',
        'MODAL_TITLE': 'Supply Details',
        'MODAL_DATE': 'Date',
        'MODAL_WOOD_TYPE': 'Wood Type',
        'MODAL_TOTAL_CFT': 'Total CFT',
        'MODAL_NET_AMOUNT': 'Net Amount',
        'TH_LOG_NO': 'Log #',
        'TH_LENGTH': 'Length (in)',
        'TH_GIRTH': 'Girth (in)',
        'TH_CFT': 'CFT',
        'TH_PRICE': 'Price',
        'TH_LINE_TOTAL': 'Line Total'
      },
      'HEADER': {
        'WELCOME': 'Welcome,',
        'SYSTEM_ADMIN': 'System Administrator',
        'PARTNER': 'Authorized Partner',
        'SEARCH_PLACEHOLDER': 'Search anything...',
        'MY_PROFILE': 'My Profile',
        'CHANGE_PASSWORD': 'Change Password',
        'LOGOUT': 'Logout',
        'ACCOUNT': 'Account'
      },
      'SIDEBAR': {
        'BRAND_TITLE_SUPPLIER': 'WFMS Supplier',
        'BRAND_SUB_SUPPLIER': 'Partner Portal',
        'BRAND_TITLE_ADMIN': 'WFMS Admin',
        'BRAND_SUB_ADMIN': 'Management System',
        'DASHBOARD': 'DASHBOARD',
        'USER_MANAGEMENT': 'USER MANAGEMENT',
        'SUPPLY_CHAIN': 'SUPPLY CHAIN',
        'SALES_CUSTOMERS': 'SALES & CUSTOMERS',
        'FINANCIALS': 'FINANCIALS',
        'INVENTORY': 'INVENTORY',
        'Overview': 'Overview',
        'Employee Overview': 'Employee Overview',
        'User Access': 'User Access',
        'Employees': 'Employees',
        'Attendance': 'Attendance',
        'Loans & Advances': 'Loans & Advances',
        'Payroll Automation': 'Payroll Automation',
        'Designation Rates': 'Designation Rates',
        'Suppliers': 'Suppliers',
        'Supply Requests': 'Supply Requests',
        'Log Management': 'Log Management',
        'Raw Material Cutting': 'Raw Material Cutting',
        'Customers': 'Customers',
        'Quotations': 'Quotations',
        'Orders': 'Orders',
        'Receipts': 'Receipts',
        'Expenses': 'Expenses',
        'Product Category': 'Product Category',
        'Stock Inventory': 'Stock Inventory',
        'Dashboard': 'Dashboard',
        'My Supplies': 'My Supplies',
        'Accounts View': 'Accounts View'
      },
      'LOGIN': {
        'BRAND_TITLE': 'Sachintha Timber Mall',
        'BRAND_SUBTITLE': 'Wood & Furniture Management System',
        'FEATURE_INVENTORY': 'Comprehensive Inventory Management',
        'FEATURE_TRACKING': 'Real-time Order Tracking',
        'FEATURE_SECURE': 'Secure & Reliable',
        'WELCOME_BACK': 'Welcome Back',
        'SIGN_IN_PROMPT': 'Please sign in to your account',
        'USERNAME': 'Username',
        'PASSWORD': 'Password',
        'USERNAME_PLACEHOLDER': 'Enter your username',
        'PASSWORD_PLACEHOLDER': 'Enter your password',
        'REMEMBER_ME': 'Remember me',
        'RESET_PASSWORD_LINK': 'Reset Password',
        'CHANGE_PASSWORD_LINK': 'Change Password?',
        'SIGN_IN_BTN': 'Sign In',
        'SIGNING_IN_BTN': 'Signing In...',
        'RESET_MODAL_TITLE': 'Reset Password?',
        'RESET_MODAL_BODY': 'Are you sure you want to reset the password for user',
        'RESET_MODAL_INFO': 'Your password will be set to the default: password123',
        'RESET_MODAL_NOTE': 'You will be required to change it immediately after logging in.',
        'CANCEL_BTN': 'Cancel',
        'CONFIRM_RESET_BTN': 'Confirm Reset',
        'SUCCESS_LOGIN': 'Login successful! Welcome back.',
        'WARNING_RESET': 'Your password has been reset. Please change it to continue.',
        'ERROR_INVALID': 'Invalid username or password',
        'ERROR_LOCKED': 'Your account has been locked. Please try again in 5 minutes.',
        'ERROR_DISABLED': 'Your account has been disabled. Please contact support.',
        'ERROR_CONNECTION': 'Unable to connect to server. Please check your connection.',
        'ERROR_GENERAL': 'An error occurred during login. Please try again.'
      },
      'CHANGE_PASSWORD': {
        'SECURE_ACCOUNT': 'Secure Your Account',
        'BRAND_SUBTITLE': 'Wood & Furniture Management System',
        'FEATURE_PROTECT': 'Protect your business data',
        'FEATURE_MANAGE': 'Manage your access securely',
        'FEATURE_ENTERPRISE': 'Enterprise-grade security',
        'TITLE': 'Change Password',
        'SUBTITLE': 'Update your login credentials',
        'USERNAME': 'Username',
        'CURRENT_PASSWORD': 'Current Password',
        'NEW_PASSWORD': 'New Password',
        'CONFIRM_PASSWORD': 'Confirm New Password',
        'USERNAME_PLACEHOLDER': 'Enter your username',
        'CURRENT_PASSWORD_PLACEHOLDER': 'Enter current password',
        'NEW_PASSWORD_PLACEHOLDER': 'At least 6 characters',
        'CONFIRM_PASSWORD_PLACEHOLDER': 'Must match new password',
        'STRENGTH_LABEL': 'Password Strength:',
        'PASSWORDS_NOT_MATCH': 'Passwords do not match',
        'UPDATE_BTN': 'Update Password',
        'UPDATING_BTN': 'Updating...',
        'CANCEL_GO_BACK': 'Cancel and go back',
        'SUCCESS_CHANGE': 'Password changed successfully! Please login with your new password.',
        'WARNING_MIN_LENGTH': 'New password must be at least 6 characters',
        'STRENGTH': {
          'WEAK': 'Weak',
          'FAIR': 'Fair',
          'GOOD': 'Good',
          'STRONG': 'Strong'
        }
      },
      'ACCOUNTS_DASHBOARD': {
        'TITLE': 'Accounts & Financial Dashboard',
        'ASSETS': 'Total Assets',
        'LIABILITIES': 'Total Liabilities',
        'WORKING_CAPITAL': 'Working Capital',
        'PROFIT_LOSS': 'Net Profit / Loss',
        'ASSET_COMPOSITION': 'Asset Composition',
        'INCOME_EXPENSE': 'Income vs Expenses',
        'FINISHED_PRODUCTS': 'Finished Products Inventory',
        'RAW_MATERIALS': 'Raw Materials Inventory (Available)',
        'NO_PRODUCTS': 'No finished products in stock',
        'NO_MATERIALS': 'No raw materials in stock',
        'EXPORT_PDF': 'Export PDF',
        'EXPORT_EXCEL': 'Export Excel (CSV)',
        'PRODUCT_NAME': 'Product',
        'AVAILABLE_QTY': 'Qty',
        'UNIT_PRICE': 'Unit Price',
        'TOTAL_VALUE': 'Total Value',
        'MATERIAL_NAME': 'Material',
        'QUANTITY_CFT': 'Qty (CFT)',
        'PRICE_PER_CFT': 'Price/CFT',
        'START_DATE': 'Start Date',
        'END_DATE': 'End Date',
        'FILTER': 'Filter',
        'CALCULATING': 'Calculating financials...',
        'PAGE': 'Page',
        'OF': 'of',
        'PREV': 'Prev',
        'NEXT': 'Next'
      },
      'ORDER_MANAGEMENT': {
        'TITLE': 'Order Management Dashboard',
        'SUBTITLE': 'Track and manage customer orders, payments and fulfillment',
        'SEARCH_PLACEHOLDER': 'Search by customer or quotation...',
        'ALL_STATUS': 'All Status',
        'NEW_ORDER': 'New Order',
        'TOTAL_ORDERS': 'Total Orders',
        'PENDING': 'Pending',
        'COMPLETED': 'Completed',
        'TOTAL_REVENUE': 'Total Revenue',
        'ORDER_LIST': 'Order List',
        'RECORDS': 'records',
        'LOADING': 'Loading orders...',
        'COL_NUM': '#',
        'COL_ORDER_NO': 'Order No.',
        'COL_QUOTE_NO': 'Quotation No.',
        'COL_CUSTOMER': 'Customer',
        'COL_DATE': 'Order Date',
        'COL_TOTAL': 'Total',
        'COL_PAID': 'Paid',
        'COL_BALANCE': 'Balance',
        'COL_STATUS': 'Status',
        'COL_ACTIONS': 'Actions',
        'NA': 'N/A',
        'NO_ORDERS': 'No orders found',
        'SHOWING': 'Showing',
        'TO': 'to',
        'OF': 'of',
        'ORDERS': 'orders',
        'PREVIOUS': 'Previous',
        'PAGE': 'Page',
        'NEXT': 'Next',
        'EDIT_ORDER': 'Edit Order',
        'CREATE_ORDER': 'Create Order',
        'UPDATE_ORDER': 'Update Order',
        'CANCEL': 'Cancel',
        'ORDER_DETAILS': 'Order Details',
        'ADD_ROW': 'Add Row',
        'COL_PRODUCT_CAT': 'Product Name',
        'COL_DESC': 'Description',
        'COL_QTY': 'Qty',
        'COL_PRICE': 'Price (Rs.)',
        'GRAND_TOTAL': 'Grand Total',
        'CLOSE': 'Close',
        'CONFIRM_DELETE': 'Confirm Delete',
        'DELETE_MSG': 'Are you sure you want to delete this order? This action cannot be undone.',
        'DELETE': 'Delete',
        'SELECT_CUSTOMER': 'Select customer',
        'SELECT': 'Select',
        'ITEM_DESC': 'Item description'
      },
      'CUSTOMER_MANAGEMENT': {
        'TITLE': 'Customer Management',
        'SUBTITLE': 'Manage customer profiles and interaction history',
        'ADD_NEW': 'Add New Customer',
        'TOTAL_CLIENTS': 'Total Clients',
        'ACTIVE_MEMBERS': 'Active Members',
        'INACTIVE_MEMBERS': 'Inactive Members',
        'ID': '#ID',
        'CUST_INFO': 'Customer Info',
        'CONTACT_DETAILS': 'Contact Details',
        'ADDRESS': 'Address',
        'CREATED_DATE': 'Created Date',
        'STATUS': 'Status',
        'ACTIONS': 'Actions',
        'ACTIVE': 'Active',
        'INACTIVE': 'Inactive',
        'EDIT_DETAILS': 'Edit Details',
        'DEACTIVATE': 'Deactivate',
        'ACTIVATE': 'Activate',
        'DELETE_RECORD': 'Delete record',
        'EDIT_TITLE': 'Edit Customer Details',
        'CUST_NAME': 'Customer Name',
        'NIC': 'NIC',
        'MOBILE': 'Mobile Number',
        'EMAIL': 'Email Address',
        'CANCEL': 'Cancel',
        'SAVE_CHANGES': 'Save Changes'
      },
      'QUOTATION_MANAGEMENT': {
        'TITLE': 'Quotation Management',
        'SUBTITLE': 'Create and manage customer quotations',
        'NEW_QUOTE': 'New Quotation',
        'TOTAL_QUOTES': 'Total Quotations',
        'PENDING_APPROVAL': 'Pending Approval',
        'CONVERTED_ORDERS': 'Converted to Orders',
        'ID': 'ID',
        'QUOTE_NO': 'Quotation No',
        'CUSTOMER': 'Customer',
        'DATE': 'Date',
        'TOTAL_AMOUNT': 'Total Amount',
        'STATUS': 'Status',
        'EXPIRY_STATUS': 'Expiry Status',
        'ACTIONS': 'Actions',
        'NA': 'N/A',
        'ALREADY_CONVERTED': 'Already Converted',
        'QUOTE_EXPIRED': 'Quotation Expired',
        'APPROVE_CONVERT': 'Approve & Convert',
        'VIEW': 'View',
        'EDIT': 'Edit',
        'DELETE': 'Delete',
        'NO_QUOTES': 'No quotations found.',
        'SHOWING': 'Showing',
        'OF': 'of',
        'PREVIOUS': 'Previous',
        'PAGE': 'Page',
        'NEXT': 'Next',
        'EDIT_QUOTE': 'Edit Quotation',
        'CREATE_QUOTE': 'Create Quotation',
        'SELECT_CUSTOMER': 'Select Customer',
        'QUOTE_DATE': 'Quotation Date',
        'GENERATING': 'Generating...',
        'VALID_UNTIL': 'Valid Until',
        'PENDING': 'Pending',
        'APPROVED': 'Approved',
        'REJECTED': 'Rejected',
        'CONVERTED': 'Converted',
        'REMARKS': 'Remarks',
        'QUOTE_ITEMS': 'Quotation Items',
        'ADD_ITEM': 'Add Item',
        'CATEGORY': 'Product Name',
        'PRODUCT_NAME': 'Item Description',
        'QTY': 'Qty',
        'PRICE': 'Price',
        'TOTAL': 'Total',
        'SEARCH_CAT': 'Search product...',
        'ITEM_NAME': 'Item name',
        'GRAND_TOTAL': 'Grand Total',
        'CANCEL': 'Cancel',
        'PROCESSING': 'Processing...',
        'UPDATE_QUOTE': 'Update Quotation',
        'CREATE_QUOTE_BTN': 'Create Quotation',
        'APPROVE_CONVERT_TITLE': 'Approve & Convert to Order',
        'APPROVE_MSG_1': 'Are you sure you want to approve',
        'APPROVE_MSG_2': 'This will convert the quotation into a customer order and redirect you to the Order Management dashboard.',
        'YES_APPROVE': 'Yes, Approve & Convert',
        'CONFIRM_DELETE_TITLE': 'Confirm Deletion',
        'DELETE_MSG_1': 'Are you sure you want to delete this quotation?',
        'DELETE_MSG_2': 'This action cannot be undone.',
        'QUOTE_ID': 'Quotation ID:',
        'YES_DELETE': 'Yes, Delete'
      },
      'ADMIN_DASHBOARD': {
        'WELCOME': 'Welcome to Sachintha Timber Mall',
        'SUBTITLE': 'Manage your wood and furniture inventory efficiently.',
        'USERS': 'Users',
        'USERS_DESC': 'Manage Staff & Roles',
        'EMPLOYEES': 'Employees',
        'EMPLOYEES_DESC': 'Staff Records & Status',
        'SUPPLIERS': 'Suppliers',
        'SUPPLIERS_DESC': 'Manage Contributors',
        'CUSTOMERS': 'Customers',
        'CUSTOMERS_DESC': 'Client Directory',
        'SUPPLY': 'Supply',
        'SUPPLY_DESC': 'Material Requests',
        'QUICK_ACTIONS': 'Quick Actions',
        'ADD_STAFF': 'Add New Staff',
        'NEW_SUPPLY': 'New Supply Request',
        'CREATE_QUOTE': 'Create Quotation',
        'CREATE_ORDER': 'Create Order',
        'LOG_MGMT': 'Log Management',
        'MATERIAL_CUTTING': 'Material Cutting',
        'RECORD_ATTENDANCE': 'Record Attendance',
        'RUN_PAYROLL': 'Run Payroll'
      },
      'EMPLOYEE_DASHBOARD': {
        'WELCOME': 'Welcome Back,',
        'SUBTITLE': 'Sachintha Timber Mall — Employee Operations Portal',
        'NO_PERMISSIONS_TITLE': 'No Permissions Assigned',
        'NO_PERMISSIONS_DESC1': 'Your user account currently has no active permissions for system modules.',
        'NO_PERMISSIONS_DESC2': 'Please contact the Administrator to request access to the necessary functions.',
        'ACCESS_MODULE': 'Access Module'
      },
      'SUPPLIER_DASHBOARD': {
        'WELCOME': 'Welcome Back,',
        'SUBTITLE': 'Sachintha Timber Mall — Supplier Partner Portal',
        'WORKSPACE': 'SUPPLIER WORKSPACE',
        'ACCESS_MODULE': 'Access Module'
      },
      'EMPLOYEE_MANAGEMENT': {
        'TITLE': 'Employee Management',
        'SUBTITLE': 'Maintain staff records and designations',
        'ADD_NEW': 'Add New Employee',
        'TOTAL_WORKFORCE': 'Total Workforce',
        'ACTIVE_STAFF': 'Active Staff',
        'ON_LEAVE_INACTIVE': 'On Leave/Inactive',
        'ID': '#ID',
        'EMP_INFO': 'Employee Info',
        'NIC': 'NIC',
        'DESIGNATION': 'Designation',
        'MOBILE': 'Mobile',
        'JOINED_DATE': 'Joined Date',
        'STATUS': 'Status',
        'ACTIONS': 'Actions',
        'ACTIVE': 'Active',
        'INACTIVE': 'Inactive',
        'EDIT_DETAILS': 'Edit Details',
        'DEACTIVATE': 'Deactivate',
        'ACTIVATE': 'Activate',
        'DELETE_RECORD': 'Delete record',
        'EDIT_TITLE': 'Edit Employee Details',
        'EMP_NAME': 'Employee Name',
        'EMAIL': 'Email Address',
        'ADDRESS': 'Address',
        'CANCEL': 'Cancel',
        'SAVE_CHANGES': 'Save Changes'
      },
      'SUPPLIER_MANAGEMENT': {
        'TITLE': 'Supplier Management',
        'SUBTITLE': 'Manage wood and material contributors',
        'ADD_NEW': 'Add New Supplier',
        'TOTAL_SUPPLIERS': 'Total Suppliers',
        'ACTIVE_CONTRIBUTORS': 'Active Contributors',
        'INACTIVE_PAUSED': 'Inactive/Paused',
        'ID': '#ID',
        'SUPP_INFO': 'Supplier Info',
        'CATEGORY': 'Category',
        'CONTACT_INFO': 'Contact Info',
        'CREATED_DATE': 'Created Date',
        'STATUS': 'Status',
        'ACTIONS': 'Actions',
        'ACTIVE': 'Active',
        'INACTIVE': 'Inactive',
        'EDIT_DETAILS': 'Edit Details',
        'DEACTIVATE': 'Deactivate',
        'ACTIVATE': 'Activate',
        'DELETE_RECORD': 'Delete record',
        'NO_SUPPLIERS': 'No suppliers found.',
        'EDIT_TITLE': 'Edit Supplier Details',
        'SUPP_NAME': 'Supplier Name',
        'MOBILE': 'Mobile Number',
        'EMAIL': 'Email',
        'ADDRESS': 'Address',
        'CANCEL': 'Cancel',
        'SAVE_CHANGES': 'Save Changes'
      },
      'ATTENDANCE_MANAGEMENT': {
        'TITLE': 'Employee Attendance',
        'SUBTITLE': 'Record and track daily attendance and work hours',
        'BULK_ACTION': 'Bulk Action',
        'ADD_RECORD': 'Add Record',
        'SEARCH_DATE': 'Search by Date',
        'FILTER_EMPLOYEE': 'Filter by Employee',
        'ALL_EMPLOYEES': 'All Employees',
        'FILTER_RECORDS': 'Filter Records',
        'EMP_DETAILS': 'Employee Details',
        'ATTENDANCE_DATE': 'Attendance Date',
        'STATUS': 'Status',
        'CHECK_IN_OUT': 'Check In / Out',
        'OVERTIME': 'Overtime',
        'REMARKS': 'Remarks',
        'ACTIONS': 'Actions',
        'NOT_RECORDED': 'Not recorded',
        'EDIT_RECORD': 'Edit Record',
        'MONTHLY_SUMMARY': 'Monthly Summary',
        'DELETE_RECORD': 'Delete Record',
        'NO_LOGS': 'No Attendance Logs',
        'NO_LOGS_DESC': 'No records found matching your current filter criteria.',
        'CLEAR_FILTERS': 'Clear All Filters',
        'EDIT_ATTENDANCE': 'Edit Attendance',
        'MARK_ATTENDANCE': 'Mark Attendance',
        'SELECT_EMPLOYEE': 'Select Employee',
        'EMPLOYEE': 'Employee',
        'ATTENDANCE_STATUS': 'Attendance Status',
        'CHECK_IN_TIME': 'Check-In Time',
        'CHECK_OUT_TIME': 'Check-Out Time',
        'REMARKS_NOTES': 'Remarks / Notes',
        'WARNING_MSG': 'A record already exists for this date. Saving will update it.',
        'SWITCH_EDIT': 'Switch to Edit',
        'CANCEL': 'Cancel',
        'UPDATE_RECORD': 'Update Record',
        'SAVE_ATTENDANCE': 'Save Attendance',
        'ANALYTICS': 'Attendance Analytics',
        'ANALYSIS_MONTH': 'Analysis Month',
        'ANALYSIS_YEAR': 'Analysis Year',
        'PRESENT': 'Present',
        'ABSENT': 'Absent',
        'HALF_DAY': 'Half Day',
        'LEAVE': 'Leave',
        'HOLIDAYS': 'Holidays',
        'WEEKENDS': 'Weekends',
        'TOTAL_OT_HRS': 'Total OT Hrs',
        'TOTAL_WORKING_DAYS': 'Total Working Days',
        'GENERATING_REPORT': 'Generating Report...',
        'CLOSE_REPORT': 'Close Report',
        'BULK_ENTRY': 'Bulk Attendance Entry',
        'ACTIVE_EMPLOYEES_BADGE': 'Active Employees',
        'IN': 'In',
        'OUT': 'Out',
        'SUBMIT_ALL': 'Submit All Records'
      },
      'LOAN_ADVANCE': {
        'TITLE': 'Loan & Advance Management',
        'SUBTITLE': 'Track employee loans, advances, and recovery rules',
        'REFRESH_DATA': 'Refresh Data',
        'TOTAL_ACTIVE_LOANS': 'Total Active Loans',
        'EXPECTED_COLLECTION': 'Expected Collection (Monthly)',
        'PENDING_REQUESTS': 'Pending Requests',
        'ISSUE_NEW': 'Issue New Loan / Advance',
        'SELECT_EMPLOYEE': 'Select Employee',
        'SELECT_EMP_OPTION': '-- Select Employee --',
        'TYPE': 'Type',
        'LOAN': 'Loan',
        'ADVANCE': 'Advance',
        'AMOUNT': 'Amount (LKR)',
        'INSTALLMENTS': 'Installments (Months)',
        'MONTHLY_DEDUCTION': 'Monthly Deduction',
        'REASON': 'Reason / Purpose',
        'ACTIVE_BALANCE_WARNING': 'Active balance:',
        'PROCESSING': 'Processing...',
        'APPLY_LOAN': 'Apply Loan & Set Rule',
        'LOAN_HISTORY': 'Loan History & Tracking',
        'EMPLOYEE': 'Employee',
        'AMOUNT_TH': 'Amount',
        'PROGRESS': 'Progress',
        'STATUS': 'Status',
        'BAL': 'Bal:',
        'NO_RECORDS': 'No records found.'
      },
      'PAYROLL_MANAGEMENT': {
        'TITLE': 'Payroll & Salary Automation',
        'SUBTITLE': 'Generate, preview and confirm monthly employee payouts',
        'PARAMETERS': 'Payroll Parameters',
        'SELECT_EMPLOYEE': 'Select Employee',
        'CHOOSE_EMP': '-- Choose Employee --',
        'MONTH': 'Month',
        'YEAR': 'Year',
        'PAYMENT_FREQ': 'Payment Frequency',
        'MONTHLY': 'Monthly',
        'DAILY_WAGE': 'Daily Wage',
        'DEDUCT_LOAN': 'Deduct Loan Installment',
        'OTHER_DEDUCTIONS': 'Other Deductions (Rs.)',
        'DEDUCTION_REASON': 'Deduction Reason',
        'LOAN_OVERRIDE': 'Loan Override (Optional)',
        'LOAN_OVERRIDE_HINT': 'Only values > auto-calculated installment are accepted.',
        'CALCULATING': 'Calculating...',
        'PREVIEW_PAYROLL': 'Preview Payroll',
        'PREVIEW_TITLE': 'Payroll Preview:',
        'EARNINGS_BREAKDOWN': 'Earnings Breakdown',
        'BASIC_SALARY': 'Basic Salary',
        'OVERTIME': 'Overtime',
        'GROSS_EARNINGS': 'Gross Earnings',
        'DEDUCTIONS_ADJ': 'Deductions & Adjustments',
        'LOAN_RECOVERY': 'Loan Recovery',
        'OTHER_DEDUCT_LBL': 'Other Deductions',
        'DAILY_WAGES_PAID': 'Daily Wages Already Paid',
        'NET_PAYABLE': 'Net Payable: Rs.',
        'DISBURSE_DESC': 'Total amount to be disbursed for the month of',
        'ATTENDANCE_FLAGS': 'Attendance Flags:',
        'CANCEL': 'Cancel',
        'FINALIZING': 'Finalizing...',
        'CONFIRM_GENERATE': 'Confirm & Generate Expense',
        'NO_PREVIEW': 'No Preview Generated',
        'NO_PREVIEW_DESC': 'Select an employee and period, then click "Preview Payroll" to see calculation details.'
      },
      'DESIGNATION_SALARY': {
        'TITLE': 'Designation Salary Management',
        'SUBTITLE': 'Set base salary rates for different roles in the company',
        'EDIT_MAPPING': 'Edit Mapping',
        'ADD_NEW': 'Add New Designation',
        'DESIG_NAME': 'Designation Name',
        'BASIC_RATE': 'Basic Salary / Rate (Rs.)',
        'RATE_TYPE': 'Rate Type',
        'DAILY_RATE': 'Daily Rate',
        'MONTHLY_FIXED': 'Monthly (Fixed)',
        'IS_ACTIVE': 'Is Active',
        'UPDATE_RATE': 'Update Rate',
        'SAVE_RATE': 'Save Rate',
        'CANCEL': 'Cancel',
        'DESIGNATION': 'Designation',
        'RATE_RS': 'Rate (Rs.)',
        'TYPE': 'Type',
        'STATUS': 'Status',
        'ACTIONS': 'Actions',
        'ACTIVE': 'Active',
        'INACTIVE': 'Inactive',
        'NO_DESIGNATIONS': 'No designations found. Add your first one to the left.'
      },
      'SUPPLY_REQUEST_MANAGEMENT': {
        'TITLE': 'Raw Material Supply Requests',
        'SUBTITLE': 'Manage supplier requests and convert them to inventory supply orders',
        'SEARCH_PLACEHOLDER': 'Search by supplier or ID...',
        'ALL_STATUS': 'All Status',
        'PENDING': 'Pending',
        'APPROVED': 'Approved',
        'PARTIALLY_APPROVED': 'Partially Approved',
        'REJECTED': 'Rejected',
        'CONVERTED': 'Converted',
        'NEW_REQUEST': 'New Request',
        'TOTAL_REQUESTS': 'Total Requests',
        'REQUEST_LIST': 'Supply Request List',
        'RECORDS': 'records',
        'LOADING': 'Loading requests...',
        'SUPPLIER': 'Supplier',
        'REQUEST_DATE': 'Request Date',
        'MATERIALS': 'Materials',
        'STATUS': 'Status',
        'ACTIONS': 'Actions',
        'NO_REQUESTS': 'No requests found',
        'SHOWING': 'Showing',
        'OF': 'of',
        'PAGE': 'Page',
        'CREATE_TITLE': 'Create New Supply Request',
        'SELECT_SUPPLIER': 'Select Supplier',
        'TRANSPORT_SUPPLIER': 'Transport by Supplier',
        'TRANSPORT_NOTES': 'Transport Notes',
        'REMARKS': 'Remarks',
        'REQUESTED_MATERIALS': 'Requested Materials',
        'ADD_MATERIAL': 'Add Material',
        'MATERIAL': 'Material',
        'REQUESTED_CFT': 'Requested CFT',
        'CANCEL': 'Cancel',
        'SEND_REQUEST': 'Send Request',
        'REVIEW_REQUEST': 'Review Request',
        'DATE': 'Date',
        'TRANSPORT': 'Transport',
        'APPROVE_QUANTITIES': 'Approve Quantities & Set Prices',
        'APPROVED_CFT': 'Approved CFT',
        'UNIT_PRICE': 'Unit Price (Rs.)',
        'TOTAL_EST': 'Total (Est.)',
        'REJECT': 'Reject',
        'APPROVE_REQ': 'Approve Request',
        'CLOSE': 'Close',
        'CONVERT_TITLE': 'Convert to Supply Order (GRN)',
        'CONVERTING': 'Converting Request',
        'FROM': 'from',
        'TARGET_VOLUME': 'Target Volume (Approved by Supplier):',
        'INVOICE_NUMBER': 'Invoice Number',
        'SUPPLY_DATE': 'Supply Date',
        'TRANSPORT_COST': 'Transport Cost (Rs.)',
        'CUTTING_FEE': 'Cutting Fee (Rs.)',
        'CUTTING_FEE_EMP': 'Cutting Fee Employee',
        'SELECT_EMP': 'Select Employee',
        'ACTUAL_LOG_DETAILS': 'Actual Log Details',
        'ADD': 'Add',
        'LOG_NO': 'Log #',
        'LENGTH': 'Length (in)',
        'GIRTH': 'Girth (in)',
        'SUPPLIER_PRICE': 'Supplier (Rs)',
        'API_PRICE': 'API Price (Rs)',
        'NEGOTIATED': 'Negotiated (Rs)',
        'CFT': 'CFT',
        'TOTAL': 'Total',
        'GRAND_SUMMARY': 'Grand Summary',
        'TARGET': 'Target:',
        'REJECT_REQ': 'Reject Request',
        'COMPLETE_ORDER': 'Complete Order & Generate GRN'
      },
      'SUPPLY_RAW_MATERIAL': {
        'TITLE': 'Add Supplier Order',
        'SUBTITLE': 'Record raw material supply logs and track additional fees',
        'SUPPLIER': 'Supplier',
        'SELECT_SUPPLIER': 'Select Supplier',
        'INVOICE_NUMBER': 'Invoice Number',
        'AUTO_GEN': 'Auto-generated on Save',
        'WOOD_TYPE': 'Wood Type',
        'LOG_NUMBER': 'Log Number',
        'LENGTH': 'Length (in)',
        'GIRTH': 'Girth (in)',
        'QTY_CFT': 'Quantity (CFT)',
        'PRICE_CFT': 'Price/CFT',
        'LINE_TOTAL': 'Line Total',
        'ADD_LOG_ROW': 'Add Another Log Row',
        'FEES_DEDUCTIONS': 'Additional Fees & Deductions',
        'TRANSPORT_CHARGES': 'Transport Charges',
        'CUTTING_FEE': 'Cutting Fee',
        'CUTTING_EMPLOYEE': 'Cutting Employee',
        'SELECT_EMP': 'Select Employee',
        'TREE_SELLER_NOTE': 'Note: These deductions are typically subtracted from the gross total for Tree Sellers.',
        'GROSS_TOTAL': 'Gross Total Amount',
        'TOTAL_DEDUCTIONS': 'Total Deductions',
        'NET_PAYABLE': 'Net Payable Amount',
        'RECORDING': 'Recording Supply...',
        'CONFIRM_GENERATE': 'Confirm & Generate GRN'
      },
      'RAW_MATERIAL_CUTTING': {
        'TITLE': 'Raw Material Cutting Process',
        'SUBTITLE': 'Select logs to visualize dimensions and record cutting output',
        'SEARCH': 'Search by Invoice or Log #...',
        'SELECT': 'Select',
        'INVOICE_NO': 'Invoice #',
        'LOG_NO': 'Log #',
        'LENGTH': 'Length (in)',
        'GIRTH': 'Girth (in)',
        'VOLUME': 'Volume (CFT)',
        'NO_LOGS': 'No matching raw materials found.',
        'VISUALIZER': 'Cylindrical Log Visualizer',
        'INVOICE_REF': 'Invoice Reference',
        'TOTAL_VOLUME': 'Total Volume',
        'FORMULA': 'Calculated via Hopper\'s Rule: (Girth² × Length) / 12',
        'SELECT_ONE': 'Select exactly one log row to visualize its dimensions',
        'GENERATED_PRODUCTS': 'Generated Products',
        'SPECIFY_PRODUCTS': 'Specify the types and quantities obtained after cutting',
        'ADD_ROW': 'Add Another Row',
        'PRODUCT_CAT': 'Product Category',
        'CHOOSE_CAT': 'Choose Category...',
        'QTY_PRODUCED': 'Quantity Produced',
        'LOGS_SELECTED': 'logs selected for processing',
        'CLEAR_ALL': 'Clear All',
        'PROCESS_CUTTING': 'Process Cutting',
        'PROCESSING': 'Processing...'
      },
      'EXPENSE_MANAGEMENT': {
        'TITLE': 'Expense Account Management',
        'SUBTITLE': 'Track, manage, and audit corporate expenditures and supplier invoices',
        'EXPENSE_DETAILS': 'Expense Details',
        'DESCRIPTION': 'Description:',
        'DATE': 'Date:',
        'AMOUNT': 'Amount:',
        'CATEGORY': 'Category:',
        'RECIPIENT': 'Recipient:',
        'GRN': 'GRN:',
        'REMARKS': 'Remarks:',
        'EXPENSE_ID': 'Expense ID:',
        'USER_ID': 'User ID:',
        'REFRESH_DATA': 'Refresh Data',
        'TOTAL_EXPENDITURE': 'Total Expenditure',
        'ACTIVE_CATEGORIES': 'Active Cost Categories',
        'MTD_COST': 'Month-to-Date Cost',
        'RECORD_NEW': 'Record New Expenditure',
        'MODIFY_ENTRY': 'Modify Expense Entry #',
        'UPDATE_DETAILS': 'Update transaction details',
        'ENTER_NEW': 'Enter a new business cost item',
        'COST_CATEGORY': 'Cost Category',
        'CHOOSE_CATEGORY': '-- Choose Category --',
        'AMOUNT_LKR': 'Amount (LKR)',
        'DATE_LABEL': 'Date',
        'PAID_TO': 'Paid To / Recipient',
        'PAID_TO_PLACEHOLDER': 'Supplier, Employee, or Vendor name',
        'DESC_LABEL': 'Description',
        'DESC_PLACEHOLDER': 'What was this expenditure for?',
        'ASSOC_GRN': 'Associated GRN (Optional)',
        'NOT_ASSOC_GRN': '-- Not Associated with GRN --',
        'AUDIT_REMARKS': 'Audit Remarks (Optional)',
        'AUDIT_PLACEHOLDER': 'Optional audit or tracking notes',
        'SAVING': 'Saving...',
        'UPDATE_TRANS': 'Update Transaction',
        'RECORD_TRANS': 'Record Transaction',
        'CANCEL': 'Cancel',
        'AUDIT_LOGS': 'Expenditure Audit Logs',
        'AUDIT_SUBTITLE': 'Search and audit recorded transactions',
        'FILTER_EXPENSES': 'Filter expenses...',
        'SORT': 'Sort:',
        'LATEST_FIRST': 'Latest First',
        'OLDEST_FIRST': 'Oldest First',
        'TRANSACTION': 'Transaction',
        'RECIPIENT_TH': 'Recipient',
        'CATEGORY_TH': 'Category',
        'AMOUNT_TH': 'Amount',
        'ACTIONS': 'Actions',
        'NOTES': 'Notes:',
        'NO_RECORDS': 'No expense records found.',
        'LOADING': 'Loading data...',
        'SHOWING': 'Showing',
        'OF': 'of',
        'PREVIOUS': 'Previous',
        'NEXT': 'Next',
        'PAGE': 'Page'
      },
      'RECEIPT_MANAGEMENT': {
        'TITLE': 'Receipt & Payment History',
        'SUBTITLE': 'Manage and view customer invoice payment allocations',
        'SEARCH_PLACEHOLDER': 'Search receipt, customer, or order...',
        'ADD_RECEIPT': 'Add Receipt',
        'TOTAL_REVENUE': 'Total Revenue Received',
        'TOTAL_RECEIPTS': 'Total Receipts Generated',
        'CASH_PAYMENTS': 'Cash Payments',
        'SORT_ORDER': 'Sort Order:',
        'LATEST_FIRST': 'Latest First (Default)',
        'OLDEST_FIRST': 'Oldest First',
        'RETRIEVING_DATA': 'Retrieving payment data...',
        'NO_RECEIPTS': 'No Receipts Recorded',
        'NO_RECEIPTS_DESC': 'We couldn\'t find any receipts matches. Click "Add Receipt" to log a new payment.',
        'RECEIPT_NO': 'Receipt Number',
        'DATE': 'Date',
        'CUSTOMER_NAME': 'Customer Name',
        'ORDER_NO': 'Order Number',
        'PAYMENT_MODE': 'Payment Mode',
        'TOTAL_AMOUNT': 'Total Amount',
        'ACTIONS': 'Actions',
        'ID': 'ID:',
        'NA': 'N/A',
        'SHOWING_PAGE': 'Showing page',
        'OF': 'of',
        'TOTAL_RECORDS': 'Total Records',
        'PREVIOUS': 'Previous',
        'NEXT': 'Next',
        'PAGE': 'Page'
      },
      'PRODUCT_CATEGORY': {
        'TITLE': 'Product Category Management',
        'SUBTITLE': 'Add and manage different wood/furniture categories',
        'EDIT_CATEGORY': 'Edit Category',
        'ADD_NEW': 'Add New Category',
        'MATERIAL_CATEGORY': 'Material Category',
        'MATERIAL_PLACEHOLDER': 'e.g. Teak Wood',
        'DESCRIPTION': 'Description',
        'DESC_PLACEHOLDER': 'Category details...',
        'UNIT': 'Unit of Measurement',
        'PRICE': 'Unit Price (LKR)',
        'UPDATE': 'Update Category',
        'CREATE': 'Create Category',
        'CANCEL': 'Cancel',
        'LIST_TITLE': 'Category List',
        'LIST_SUBTITLE': 'Search and manage product categories',
        'SEARCH': 'Search categories...',
        'TH_CATEGORY': 'CATEGORY',
        'TH_UNIT': 'UNIT',
        'TH_PRICE': 'PRICE',
        'TH_ACTIONS': 'ACTIONS',
        'LOADING': 'Loading categories...',
        'NO_CATEGORIES': 'No matching categories found.',
        'NO_CATEGORIES_ADD': 'No categories found. Add your first one!',
        'SHOWING': 'Showing',
        'OF': 'of',
        'PREVIOUS': 'Previous',
        'NEXT': 'Next',
        'PAGE': 'Page'
      },
      'PRODUCT_STOCK': {
        'TITLE': 'Stock Inventory',
        'SUBTITLE': 'Real-time overview of current material categories and available stock volumes',
        'REFRESH': 'Refresh',
        'TH_STOCK_ID': 'Stock ID',
        'TH_MATERIAL_CATEGORY': 'Material Category',
        'TH_DESCRIPTION': 'Description',
        'TH_UNIT': 'Unit of Measurement',
        'TH_PRICE': 'Unit Price',
        'TH_AVAILABLE_QTY': 'Available Qty',
        'LOADING': 'Loading...',
        'NO_RECORDS': 'No stock records found matching your search.'
      },
      'SUPPLY_RAW_MATERIAL_DASHBOARD': {
        'TITLE': 'Log Management',
        'SUBTITLE': 'View and manage all recorded raw material supply orders',
        'SEARCH_PLACEHOLDER': 'Search by Supplier or Invoice...',
        'NEW_ORDER': 'New Supply Order',
        'TOTAL_ORDERS': 'Total Supply Orders',
        'TOTAL_MATERIAL': 'Total Material (CFT)',
        'GROSS_EXPENDITURE': 'Gross Expenditure',
        'LOADING': 'Loading supply records...',
        'TH_ID': 'ID',
        'TH_INVOICE': 'Invoice #',
        'TH_SUPPLIER': 'Supplier',
        'TH_DATE': 'Date',
        'TH_WOOD_TYPE': 'Wood Type',
        'TH_TOTAL_CFT': 'Total CFT',
        'TH_NET_AMOUNT': 'Net Amount',
        'TH_GRN_STATUS': 'GRN Status',
        'TH_ACTIONS': 'Actions',
        'GRN_CREATED': 'GRN CREATED',
        'PENDING': 'PENDING',
        'NO_RECORDS': 'No supply orders recorded yet.',
        'SHOWING': 'Showing',
        'OF': 'of',
        'PREVIOUS': 'Previous',
        'NEXT': 'Next',
        'PAGE': 'Page',
        'DETAILS_TITLE': 'Supply Details',
        'INVOICE': 'Invoice:',
        'WOOD_TYPE_MAIN': 'Wood Type (Main)',
        'LOG_BREAKDOWN': 'Log Details Breakdown',
        'LOG_NO': 'Log #',
        'L_FT': 'L (in)',
        'G_IN': 'G (in)',
        'QTY_CFT': 'Qty (CFT)',
        'PRICE_CFT': 'Price (per CFT)',
        'LINE_TOTAL': 'Line Total',
        'TOTAL_MATERIAL_VOL': 'Total Material Volume',
        'CLOSE': 'Close',
        'VIEW_GRN': 'View GRN Invoice'
      },

      'USER_MANAGEMENT_DASHBOARD': {
        'TITLE': 'User Management',
        'SUBTITLE': 'Manage system users, roles, and access status',
        'ADD_NEW_USER': 'Add New User',
        'SYSTEM_USERS': 'System Users',
        'ACTIVE_ACCESS': 'Active Access',
        'RESTRICTED': 'Restricted/Deactivated',
        'TH_ID': '#ID',
        'TH_USER_INFO': 'User Info',
        'TH_NIC': 'NIC',
        'TH_ROLE': 'Role',
        'TH_STATUS': 'Status',
        'TH_LAST_LOGIN': 'Last Login',
        'TH_ACTIONS': 'Actions',
        'ROLE_ADMIN': 'Admin',
        'ROLE_EMPLOYEE': 'Employee',
        'ACTIVE': 'Active',
        'INACTIVE': 'Inactive',
        'NEVER': 'Never',
        'CANCEL': 'Cancel',
        'CONFIRM': 'Confirm',
        'MANAGE_PRIVILEGES': 'Manage Employee Privileges',
        'CONFIGURE_ACCESS': 'Configure function access for',
        'SAVE_CHANGES': 'Save Changes'
      },

      'DASHBOARD_CARDS': {
        'EMPLOYEES': 'Employees',
        'EMPLOYEES_DESC': 'Manage employee details, profiles, and designations.',
        'ATTENDANCE': 'Attendance',
        'ATTENDANCE_DESC': 'Log and track employee daily attendance.',
        'LOANS': 'Loans & Advances',
        'LOANS_DESC': 'Approve and monitor employee loans and advances.',
        'PAYROLL': 'Payroll Automation',
        'PAYROLL_DESC': 'Process payroll, salary, and generate paysheets.',
        'DESIGNATION': 'Designation Rates',
        'DESIGNATION_DESC': 'Set salary rates for different designations.',
        
        'SUPPLIERS': 'Suppliers',
        'SUPPLIERS_DESC': 'Register and manage raw wood suppliers.',
        'SUPPLY_REQUESTS': 'Supply Requests',
        'SUPPLY_REQUESTS_DESC_EMP': 'Create and track timber supply requests.',
        'SUPPLY_REQUESTS_DESC_SUP': 'Review timber requests, confirm availability, and approve supply volumes.',
        'LOG_MGMT': 'Log Management',
        'LOG_MGMT_DESC': 'Track wood log supply, timber volume, and stock.',
        'MATERIAL_CUTTING': 'Material Cutting',
        'MATERIAL_CUTTING_DESC': 'Process wood cutting and output stock.',
        
        'CUSTOMERS': 'Customers',
        'CUSTOMERS_DESC': 'Manage customer records and details.',
        'QUOTATIONS': 'Quotations',
        'QUOTATIONS_DESC': 'Create and send quotes to customers.',
        'ORDERS': 'Orders',
        'ORDERS_DESC': 'Manage furniture production orders.',
        'RECEIPTS': 'Receipts',
        'RECEIPTS_DESC': 'Manage customer receipts and incoming payments.',
        
        'EXPENSES': 'Expenses',
        'EXPENSES_DESC': 'Track production, operational, and general expenses.',
        'PRODUCT_CATEGORY': 'Product Category',
        'PRODUCT_CATEGORY_DESC': 'Manage furniture categories and wood types.',

        'MY_SUPPLIES': 'My Supplies',
        'MY_SUPPLIES_DESC': 'View raw material supply orders recorded under your supplier account.',
        'PROFILE': 'Profile',
        'PROFILE_DESC': 'Keep your supplier account, contact, and business details up to date.',

        'CAT_USER_MGMT': 'USER MANAGEMENT',
        'CAT_SUPPLY_CHAIN': 'SUPPLY CHAIN',
        'CAT_SALES_CUSTOMERS': 'SALES & CUSTOMERS',
        'CAT_FINANCIALS': 'FINANCIALS',
        'CAT_INVENTORY': 'INVENTORY'
      }
    },
    si: {
      'PAGE_TITLES': {
        'User Login': 'පරිශීලක පිවිසුම',
        'Register New User': 'නව පරිශීලකයෙකු ලියාපදිංචි කරන්න',
        'Admin Dashboard': 'පරිපාලක උපකරණ පුවරුව',
        'Employee Dashboard': 'සේවක උපකරණ පුවරුව',
        'User Management': 'පරිශීලක කළමනාකරණය',
        'Employee Management': 'සේවක කළමනාකරණය',
        'Supplier Management': 'සැපයුම්කරු කළමනාකරණය',
        'Customer Management': 'පාරිභෝගික කළමනාකරණය',
        'Change Password': 'මුරපදය වෙනස් කරන්න',
        'User Profile': 'පරිශීලක පැතිකඩ',
        'Supplier Dashboard': 'සැපයුම්කරු උපකරණ පුවරුව',
        'My Supplies': 'මගේ සැපයුම්',
        'Order Management': 'ඇණවුම් කළමනාකරණය',
        'Quotation Management': 'මිල කැඳවීම් කළමනාකරණය',
        'Product Category': 'නිෂ්පාදන ප්‍රවර්ගය',
        'Attendance Management': 'පැමිණීමේ කළමනාකරණය',
        'Loan & Advance Management': 'ණය සහ අත්තිකාරම් කළමනාකරණය',
        'Payroll Automation': 'වැටුප් ගෙවීම් ස්වයංක්‍රීයකරණය',
        'Designation Salary Settings': 'තනතුරු වැටුප් සැකසුම්',
        'Log Management History': 'දැව කඳන් කළමනාකරණ ඉතිහාසය',
        'Add Supply Order': 'සැපයුම් ඇණවුම එකතු කරන්න',
        'Raw Material Cutting': 'අමුද්‍රව්‍ය කැපීම',
        'Supply Request Management': 'සැපයුම් ඉල්ලීම් කළමනාකරණය',
        'GRN Invoice': 'GRN ඉන්වොයිසිය',
        'Receipt Dashboard': 'රිසිට්පත් උපකරණ පුවරුව',
        'Add Receipt': 'රිසිට්පතක් එකතු කරන්න',
        'Printable Receipt': 'මුද්‍රණය කළ හැකි රිසිට්පත',
        'Expense Management': 'වියදම් කළමනාකරණය',
        'Stock Inventory': 'තොග ගබඩාව',
        'Accounts Dashboard': 'ගිණුම් උපකරණ පුවරුව'
      },
      'REGISTER_USER': {
        'CREATE_TITLE': 'පද්ධති පරිශීලකයෙකු සාදන්න',
        'CREATE_SUBTITLE': 'නව කාර්ය මණ්ඩලය සඳහා භූමිකාවන් සහ අක්තපත්‍ර අනුයුක්ත කරන්න',
        'BACK_TO_DIRECTORY': 'නාමාවලිය වෙත ආපසු',
        'REGISTRATION_TYPE': 'ලියාපදිංචි කිරීමේ වර්ගය',
        'SYSTEM_USER': 'පද්ධති පරිශීලක',
        'NON_SYSTEM_USER': 'පද්ධති නොවන පරිශීලක',
        'USER_ROLE': 'පරිශීලක භූමිකාව',
        'ENTITY_TYPE': 'ආයතන වර්ගය',
        'ROLE_EMPLOYEE': 'සේවකයා',
        'ROLE_SUPPLIER': 'සැපයුම්කරු',
        'ROLE_CUSTOMER': 'පාරිභෝගිකයා',
        'AUTH_DETAILS': 'සත්‍යාපන විස්තර',
        'USERNAME': 'පරිශීලක නාමය',
        'PASSWORD': 'මුරපදය',
        'CONFIRM_PASSWORD': 'මුරපදය තහවුරු කරන්න',
        'DETAILS': 'විස්තර',
        'FULL_NAME': 'සම්පූර්ණ නම / ආයතනයේ නම',
        'MOBILE': 'ජංගම දුරකථන අංකය',
        'EMAIL': 'විද්‍යුත් තැපෑල',
        'ADDRESS': 'ලිපිනය',
        'NIC': 'ජා.හැ.ප. අංකය',
        'DESIGNATION': 'තනතුර',
        'DATE_JOINED': 'බැඳුණු දිනය',
        'SUPPLIER_CATEGORY': 'සැපයුම්කරු වර්ගය',
        'SUP_CAT_REGULAR': 'සාමාන්‍ය (පද්ධති ප්‍රවේශය අවශ්‍යයි)',
        'SUP_CAT_LOCAL': 'දේශීය',
        'SUP_CAT_INTERNATIONAL': 'ජාත්‍යන්තර',
        'SUP_CAT_SPECIALIZED': 'විශේෂිත',
        'BTN_PROCESSING': 'සැකසෙමින් පවතී...',
        'BTN_COMPLETE': 'ලියාපදිංචිය සම්පූර්ණ කරන්න',
        'BTN_CANCEL': 'අවලංගු කරන්න'
      },
      'USER_PROFILE': {
        'EDIT_PROFILE': 'පැතිකඩ සංස්කරණය කරන්න',
        'USER_INFO': 'පරිශීලක තොරතුරු',
        'USERNAME': 'පරිශීලක නාමය:',
        'SYSTEM_ID': 'පද්ධති හැඳුනුම්පත:',
        'EMAIL': 'විද්‍යුත් තැපෑල:',
        'PHONE': 'දුරකථන අංකය:',
        'MEMBER_SINCE': 'සාමාජිකත්වය ආරම්භය:',
        'LAST_LOGIN': 'අවසන් පිවිසුම:',
        'BIO': 'පැතිකඩ විස්තර:',
        'NOT_PROVIDED': 'සපයා නැත',
        'NO_BIO': 'අමතර විස්තර සපයා නැත.',
        'SAVE_CHANGES': 'වෙනස්කම් සුරකින්න',
        'CANCEL': 'අවලංගු කරන්න',
        'ACCOUNT_ACTIVE': 'ගිණුම සක්‍රියයි',
        'ACCOUNT_INACTIVE': 'ගිණුම අක්‍රියයි',
        'SECURE_MSG': 'ඔබගේ ගිණුම 256-bit JWT සංකේතනය මගින් ආරක්ෂා කර ඇත.',
        'UPDATE_SECURITY': 'ආරක්ෂාව යාවත්කාලීන කරන්න',
        'SYS_PERMS': 'පද්ධති අවසරයන්',
        'PERM_DASHBOARD': 'උපකරණ පුවරුවට ප්‍රවේශය',
        'PERM_MANAGE': 'සම්පත් කළමනාකරණය',
        'PERM_ADMIN': 'පරිපාලක පාලනයන්',
        'PERM_REPORTS': 'වාර්තා බැලීම'
      },
      'MY_SUPPLIES': {
        'TITLE': 'මගේ සැපයුම්',
        'SUBTITLE': 'ඔබේ සැපයුම්කරු ගිණුම සඳහා වාර්තා කර ඇති අමුද්‍රව්‍ය ඇණවුම්',
        'SEARCH_PLACEHOLDER': 'ඉන්වොයිසිය, දැව වර්ගය හෝ දිනය සොයන්න',
        'LOGIN': 'පිවිසුම',
        'ROLE': 'භූමිකාව',
        'EMAIL': 'විද්‍යුත් තැපෑල',
        'NOT_SPECIFIED': 'සඳහන් කර නැත',
        'TOTAL_ORDERS': 'මුළු ඇණවුම්',
        'TOTAL_MATERIAL': 'මුළු ද්‍රව්‍ය',
        'TOTAL_NET_AMOUNT': 'මුළු ශුද්ධ මුදල',
        'LOADING': 'ඔබේ සැපයුම් වාර්තා පූරණය වෙමින් පවතී...',
        'TH_INVOICE': 'ඉන්වොයිසිය',
        'TH_DATE': 'දිනය',
        'TH_WOOD_TYPE': 'දැව වර්ගය',
        'TH_TOTAL_CFT': 'මුළු CFT',
        'TH_NET_AMOUNT': 'ශුද්ධ මුදල',
        'TH_GRN': 'GRN',
        'TH_ACTION': 'ක්‍රියාව',
        'STATUS_CREATED': 'සාදන ලදි',
        'STATUS_PENDING': 'පොරොත්තු',
        'NO_RECORDS': 'ඔබගේ ගිණුම සඳහා සැපයුම් වාර්තා හමු නොවීය.',
        'MODAL_TITLE': 'සැපයුම් විස්තර',
        'MODAL_DATE': 'දිනය',
        'MODAL_WOOD_TYPE': 'දැව වර්ගය',
        'MODAL_TOTAL_CFT': 'මුළු CFT',
        'MODAL_NET_AMOUNT': 'ශුද්ධ මුදල',
        'TH_LOG_NO': 'කඳ #',
        'TH_LENGTH': 'දිග (අඟල්)',
        'TH_GIRTH': 'වටප්‍රමාණය (අඟල්)',
        'TH_CFT': 'CFT',
        'TH_PRICE': 'මිල',
        'TH_LINE_TOTAL': 'රේඛා එකතුව'
      },
      'HEADER': {
        'WELCOME': 'ආයුබෝවන්,',
        'SYSTEM_ADMIN': 'පද්ධති පරිපාලක',
        'PARTNER': 'බලයලත් හවුල්කරු',
        'SEARCH_PLACEHOLDER': 'ඕනෑම දෙයක් සොයන්න...',
        'MY_PROFILE': 'මගේ ගිණුම',
        'CHANGE_PASSWORD': 'මුරපදය වෙනස් කරන්න',
        'LOGOUT': 'පිටවීම',
        'ACCOUNT': 'ගිණුම'
      },
      'SIDEBAR': {
        'BRAND_TITLE_SUPPLIER': 'WFMS සැපයුම්කරු',
        'BRAND_SUB_SUPPLIER': 'හවුල්කාර ද්වාරය',
        'BRAND_TITLE_ADMIN': 'WFMS පරිපාලක',
        'BRAND_SUB_ADMIN': 'කළමනාකරණ පද්ධතිය',
        'DASHBOARD': 'උපකරණ පුවරුව',
        'USER_MANAGEMENT': 'පරිශීලක කළමනාකරණය',
        'SUPPLY_CHAIN': 'සැපයුම් දාමය',
        'SALES_CUSTOMERS': 'විකුණුම් සහ පාරිභෝගිකයින්',
        'FINANCIALS': 'මූල්‍ය කටයුතු',
        'INVENTORY': 'තොග ගබඩාව',
        'Overview': 'දළ විශ්ලේෂණය',
        'Employee Overview': 'සේවක දළ විශ්ලේෂණය',
        'User Access': 'පරිශීලක ප්‍රවේශය',
        'Employees': 'සේවකයින්',
        'Attendance': 'පැමිණීම',
        'Loans & Advances': 'ණය සහ අත්තිකාරම්',
        'Payroll Automation': 'වැටුප් ස්වයංක්‍රීයකරණය',
        'Designation Rates': 'තනතුරු අනුපාත',
        'Suppliers': 'සැපයුම්කරුවන්',
        'Supply Requests': 'සැපයුම් ඉල්ලීම්',
        'Log Management': 'කොටන් කළමනාකරණය',
        'Raw Material Cutting': 'අමුද්‍රව්‍ය කැපීම',
        'Customers': 'පාරිභෝගිකයින්',
        'Quotations': 'මිල ගණන් කැඳවීම්',
        'Orders': 'ඇණවුම්',
        'Receipts': 'රිසිට්පත්',
        'Expenses': 'වියදම්',
        'Product Category': 'නිෂ්පාදන කාණ්ඩය',
        'Stock Inventory': 'තොග ඉන්වෙන්ට්රිය',
        'Dashboard': 'ප්‍රධාන පුවරුව',
        'My Supplies': 'මගේ සැපයුම්',
        'Accounts View': 'ගිණුම් දසුන'
      },
      'LOGIN': {
        'BRAND_TITLE': 'සචින්ත ලී මෝල ',
        'BRAND_SUBTITLE': 'ලී සහ ගෘහ භාණ්ඩ කළමනාකරණ පද්ධතිය',
        'FEATURE_INVENTORY': 'විස්තීර්ණ තොග කළමනාකරණය',
        'FEATURE_TRACKING': 'තත්‍ය කාලීන ඇණවුම් ලුහුබැඳීම',
        'FEATURE_SECURE': 'ආරක්ෂිත සහ විශ්වසනීය',
        'WELCOME_BACK': 'නැවත සාදරයෙන් පිළිගනිමු',
        'SIGN_IN_PROMPT': 'කරුණාකර ඔබගේ ගිණුමට ඇතුළු වන්න',
        'USERNAME': 'පරිශීලක නාමය',
        'PASSWORD': 'මුරපදය',
        'USERNAME_PLACEHOLDER': 'ඔබගේ පරිශීලක නාමය ඇතුළත් කරන්න',
        'PASSWORD_PLACEHOLDER': 'ඔබගේ මුරපදය ඇතුළත් කරන්න',
        'REMEMBER_ME': 'මතක තබා ගන්න',
        'RESET_PASSWORD_LINK': 'මුරපදය නැවත සකසන්න',
        'CHANGE_PASSWORD_LINK': 'මුරපදය වෙනස් කරන්න?',
        'SIGN_IN_BTN': 'ඇතුළු වන්න',
        'SIGNING_IN_BTN': 'ඇතුළු වෙමින්...',
        'RESET_MODAL_TITLE': 'මුරපදය නැවත සකසන්නද?',
        'RESET_MODAL_BODY': 'පරිශීලකයා සඳහා මුරපදය නැවත සැකසීමට ඔබට විශ්වාසද?',
        'RESET_MODAL_INFO': 'ඔබගේ මුරපදය පෙරනිමියට සැකසෙනු ඇත: password123',
        'RESET_MODAL_NOTE': 'ඇතුළු වූ වහාම එය වෙනස් කිරීමට ඔබට අවශ්‍ය වනු ඇත.',
        'CANCEL_BTN': 'අවලංගු කරන්න',
        'CONFIRM_RESET_BTN': 'නැවත සැකසීම තහවුරු කරන්න',
        'SUCCESS_LOGIN': 'ප්‍රවිෂ්ට වීම සාර්ථකයි! නැවත සාදරයෙන් පිළිගනිමු.',
        'WARNING_RESET': 'ඔබේ මුරපදය නැවත සකසා ඇත. කරුණාකර ඉදිරියට යාමට එය වෙනස් කරන්න.',
        'ERROR_INVALID': 'වලංගු නොවන පරිශීලක නාමයක් හෝ මුරපදයක්',
        'ERROR_LOCKED': 'ඔබගේ ගිණුම අගුලු දමා ඇත. කරුණාකර මිනිත්තු 5කින් නැවත උත්සාහ කරන්න.',
        'ERROR_DISABLED': 'ඔබගේ ගිණුම අක්‍රිය කර ඇත. කරුණාකර සහාය අමතන්න.',
        'ERROR_CONNECTION': 'සේවාදායකයට සම්බන්ධ වීමට නොහැක. කරුණාකර ඔබේ සම්බන්ධතාවය පරීක්ෂා කරන්න.',
        'ERROR_GENERAL': 'ඇතුළු වීමේදී දෝෂයක් ඇති විය. කරුණාකර නැවත උත්සාහ කරන්න.'
      },
      'CHANGE_PASSWORD': {
        'SECURE_ACCOUNT': 'ඔබේ ගිණුම සුරක්ෂිත කරන්න',
        'BRAND_SUBTITLE': 'ලී සහ ගෘහ භාණ්ඩ කළමනාකරණ පද්ධතිය',
        'FEATURE_PROTECT': 'ඔබේ ව්‍යාපාරික දත්ත සුරකින්න',
        'FEATURE_MANAGE': 'ඔබේ ප්‍රවේශය ආරක්ෂිතව කළමනාකරණය කරන්න',
        'FEATURE_ENTERPRISE': 'ව්‍යවසාය මට්ටමේ ආරක්ෂාව',
        'TITLE': 'මුරපදය වෙනස් කරන්න',
        'SUBTITLE': 'ඔබගේ ප්‍රවිෂ්ට අක්තපත්‍ර යාවත්කාලීන කරන්න',
        'USERNAME': 'පරිශීලක නාමය',
        'CURRENT_PASSWORD': 'වත්මන් මුරපදය',
        'NEW_PASSWORD': 'නව මුරපදය',
        'CONFIRM_PASSWORD': 'නව මුරපදය තහවුරු කරන්න',
        'USERNAME_PLACEHOLDER': 'පරිශීලක නාමය ඇතුළත් කරන්න',
        'CURRENT_PASSWORD_PLACEHOLDER': 'වත්මන් මුරපදය ඇතුළත් කරන්න',
        'NEW_PASSWORD_PLACEHOLDER': 'අවම වශයෙන් අක්ෂර 6 ක්',
        'CONFIRM_PASSWORD_PLACEHOLDER': 'නව මුරපදයට සමාන විය යුතුය',
        'STRENGTH_LABEL': 'මුරපද ශක්තිය:',
        'PASSWORDS_NOT_MATCH': 'මුරපද නොගැලපේ',
        'UPDATE_BTN': 'මුරපදය යාවත්කාලීන කරන්න',
        'UPDATING_BTN': 'යාවත්කාලීන වෙමින්...',
        'CANCEL_GO_BACK': 'අවලංගු කර ආපසු යන්න',
        'SUCCESS_CHANGE': 'මුරපදය සාර්ථකව වෙනස් කරන ලදී! කරුණාකර ඔබගේ නව මුරපදය සමඟ ඇතුළු වන්න.',
        'WARNING_MIN_LENGTH': 'නව මුරපදය අවම වශයෙන් අක්ෂර 6 ක් විය යුතුය',
        'STRENGTH': {
          'WEAK': 'දුර්වල',
          'FAIR': 'සාමාන්‍ය',
          'GOOD': 'හොඳ',
          'STRONG': 'ශක්තිමත්'
        }
      },
      'ACCOUNTS_DASHBOARD': {
        'TITLE': 'ගිණුම් සහ මූල්‍ය පුවරුව',
        'ASSETS': 'මුළු වත්කම්',
        'LIABILITIES': 'මුළු බැරකම්',
        'WORKING_CAPITAL': 'ක්‍රියාකාරී ප්‍රාග්ධනය',
        'PROFIT_LOSS': 'ශුද්ධ ලාභය / අලාභය',
        'ASSET_COMPOSITION': 'වත්කම් සංයුතිය',
        'INCOME_EXPENSE': 'ආදායම් සහ වියදම්',
        'FINISHED_PRODUCTS': 'නිමි භාණ්ඩ තොගය',
        'RAW_MATERIALS': 'අමුද්‍රව්‍ය තොගය (පවතින)',
        'NO_PRODUCTS': 'තොගයේ නිමි භාණ්ඩ නොමැත',
        'NO_MATERIALS': 'තොගයේ අමුද්‍රව්‍ය නොමැත',
        'EXPORT_PDF': 'PDF ලෙස ගන්න',
        'EXPORT_EXCEL': 'Excel ලෙස ගන්න',
        'PRODUCT_NAME': 'නිෂ්පාදනය',
        'AVAILABLE_QTY': 'ප්‍රමාණය',
        'UNIT_PRICE': 'ඒකක මිල',
        'TOTAL_VALUE': 'මුළු වටිනාකම',
        'MATERIAL_NAME': 'අමුද්‍රව්‍ය',
        'QUANTITY_CFT': 'ප්‍රමාණය (CFT)',
        'PRICE_PER_CFT': 'CFT මිල',
        'START_DATE': 'ආරම්භක දිනය',
        'END_DATE': 'අවසන් දිනය',
        'FILTER': 'පෙරහන් කරන්න',
        'CALCULATING': 'මූල්‍ය ගණනය කරමින්...',
        'PAGE': 'පිටුව',
        'OF': 'සිට',
        'PREV': 'පෙර',
        'NEXT': 'ඊළඟ'
      },
      'ORDER_MANAGEMENT': {
        'TITLE': 'ඇණවුම් කළමනාකරණ පුවරුව',
        'SUBTITLE': 'පාරිභෝගික ඇණවුම්, ගෙවීම් සහ සම්පූර්ණ කිරීම් හඹා යන්න',
        'SEARCH_PLACEHOLDER': 'පාරිභෝගිකයා හෝ මිල ගණන් අනුව සොයන්න...',
        'ALL_STATUS': 'සියලුම තත්වයන්',
        'NEW_ORDER': 'නව ඇණවුමක්',
        'TOTAL_ORDERS': 'මුළු ඇණවුම්',
        'PENDING': 'පොරොත්තුවෙන් පවතින',
        'COMPLETED': 'සම්පූර්ණ කරන ලද',
        'TOTAL_REVENUE': 'මුළු ආදායම',
        'ORDER_LIST': 'ඇණවුම් ලැයිස්තුව',
        'RECORDS': 'වාර්තා',
        'LOADING': 'ඇණවුම් පූරණය වෙමින්...',
        'COL_NUM': '#',
        'COL_ORDER_NO': 'ඇණවුම් අංකය',
        'COL_QUOTE_NO': 'මිල ගණන් අංකය',
        'COL_CUSTOMER': 'පාරිභෝගිකයා',
        'COL_DATE': 'ඇණවුම් දිනය',
        'COL_TOTAL': 'එකතුව',
        'COL_PAID': 'ගෙවූ මුදල',
        'COL_BALANCE': 'ඉතිරි මුදල',
        'COL_STATUS': 'තත්වය',
        'COL_ACTIONS': 'ක්‍රියා',
        'NA': 'අදාළ නොවේ',
        'NO_ORDERS': 'ඇණවුම් කිසිවක් හමු නොවීය',
        'SHOWING': 'පෙන්වන්නේ',
        'TO': 'සිට',
        'OF': 'දක්වා (මුළු:',
        'ORDERS': 'ඇණවුම්)',
        'PREVIOUS': 'පෙර',
        'PAGE': 'පිටුව',
        'NEXT': 'ඊළඟ',
        'EDIT_ORDER': 'ඇණවුම සංස්කරණය කරන්න',
        'CREATE_ORDER': 'ඇණවුම සාදන්න',
        'UPDATE_ORDER': 'ඇණවුම යාවත්කාලීන කරන්න',
        'CANCEL': 'අවලංගු කරන්න',
        'ORDER_DETAILS': 'ඇණවුම් විස්තර',
        'ADD_ROW': 'පේළියක් එක් කරන්න',
        'COL_PRODUCT_CAT': 'නිෂ්පාදනයේ නම',
        'COL_DESC': 'විස්තරය',
        'COL_QTY': 'ප්‍රමාණය',
        'COL_PRICE': 'මිල (රු.)',
        'GRAND_TOTAL': 'මුළු එකතුව',
        'CLOSE': 'වසන්න',
        'CONFIRM_DELETE': 'මකා දැමීම තහවුරු කරන්න',
        'DELETE_MSG': 'මෙම ඇණවුම මකා දැමීමට ඔබට විශ්වාසද? මෙය ආපසු හැරවිය නොහැක.',
        'DELETE': 'මකා දමන්න',
        'SELECT_CUSTOMER': 'පාරිභෝගිකයෙකු තෝරන්න',
        'SELECT': 'තෝරන්න',
        'ITEM_DESC': 'අයිතම විස්තරය'
      },
      'CUSTOMER_MANAGEMENT': {
        'TITLE': 'පාරිභෝගික කළමනාකරණය',
        'SUBTITLE': 'පාරිභෝගික පැතිකඩ සහ අන්තර්ක්‍රියා ඉතිහාසය කළමනාකරණය කරන්න',
        'ADD_NEW': 'නව පාරිභෝගිකයෙකු එක් කරන්න',
        'TOTAL_CLIENTS': 'මුළු ගනුදෙනුකරුවන්',
        'ACTIVE_MEMBERS': 'ක්‍රියාකාරී සාමාජිකයින්',
        'INACTIVE_MEMBERS': 'අක්‍රිය සාමාජිකයින්',
        'ID': '#හැඳුනුම්පත',
        'CUST_INFO': 'පාරිභෝගික තොරතුරු',
        'CONTACT_DETAILS': 'සම්බන්ධතා විස්තර',
        'ADDRESS': 'ලිපිනය',
        'CREATED_DATE': 'නිර්මාණය කළ දිනය',
        'STATUS': 'තත්වය',
        'ACTIONS': 'ක්‍රියා',
        'ACTIVE': 'ක්‍රියාකාරී',
        'INACTIVE': 'අක්‍රිය',
        'EDIT_DETAILS': 'විස්තර සංස්කරණය කරන්න',
        'DEACTIVATE': 'අක්‍රිය කරන්න',
        'ACTIVATE': 'සක්‍රිය කරන්න',
        'DELETE_RECORD': 'වාර්තාව මකා දමන්න',
        'EDIT_TITLE': 'පාරිභෝගික විස්තර සංස්කරණය',
        'CUST_NAME': 'පාරිභෝගික නාමය',
        'NIC': 'ජා.හැ.අ.',
        'MOBILE': 'ජංගම දුරකථන අංකය',
        'EMAIL': 'විද්‍යුත් තැපැල් ලිපිනය',
        'CANCEL': 'අවලංගු කරන්න',
        'SAVE_CHANGES': 'වෙනස්කම් සුරකින්න'
      },
      'QUOTATION_MANAGEMENT': {
        'TITLE': 'මිල ගණන් කළමනාකරණය',
        'SUBTITLE': 'පාරිභෝගික මිල ගණන් සාදන්න සහ කළමනාකරණය කරන්න',
        'NEW_QUOTE': 'නව මිල ගණන් පත්‍රයක්',
        'TOTAL_QUOTES': 'මුළු මිල ගණන් පත්‍ර',
        'PENDING_APPROVAL': 'අනුමතය බලාපොරොත්තුවෙන්',
        'CONVERTED_ORDERS': 'ඇණවුම් බවට පත් කරන ලද',
        'ID': 'හැඳුනුම්පත',
        'QUOTE_NO': 'මිල ගණන් අංකය',
        'CUSTOMER': 'පාරිභෝගිකයා',
        'DATE': 'දිනය',
        'TOTAL_AMOUNT': 'මුළු එකතුව',
        'STATUS': 'තත්වය',
        'EXPIRY_STATUS': 'කල් ඉකුත් වීමේ තත්වය',
        'ACTIONS': 'ක්‍රියා',
        'NA': 'අදාළ නොවේ',
        'ALREADY_CONVERTED': 'දැනටමත් පරිවර්තනය කර ඇත',
        'QUOTE_EXPIRED': 'කල් ඉකුත් වී ඇත',
        'APPROVE_CONVERT': 'අනුමත කර පරිවර්තනය කරන්න',
        'VIEW': 'බලන්න',
        'EDIT': 'සංස්කරණය',
        'DELETE': 'මකා දමන්න',
        'NO_QUOTES': 'මිල ගණන් පත්‍ර හමු නොවීය.',
        'SHOWING': 'පෙන්වන්නේ',
        'OF': 'සිට',
        'PREVIOUS': 'පෙර',
        'PAGE': 'පිටුව',
        'NEXT': 'ඊළඟ',
        'EDIT_QUOTE': 'මිල ගණන් පත්‍රය සංස්කරණය',
        'CREATE_QUOTE': 'මිල ගණන් පත්‍රය සාදන්න',
        'SELECT_CUSTOMER': 'පාරිභෝගිකයා තෝරන්න',
        'QUOTE_DATE': 'මිල ගණන් දිනය',
        'GENERATING': 'සාදමින්...',
        'VALID_UNTIL': 'වලංගු දිනය',
        'PENDING': 'පොරොත්තුවෙන්',
        'APPROVED': 'අනුමත කරන ලදී',
        'REJECTED': 'ප්‍රතික්ෂේප කරන ලදී',
        'CONVERTED': 'පරිවර්තනය කරන ලදී',
        'REMARKS': 'සටහන්',
        'QUOTE_ITEMS': 'අයිතම',
        'ADD_ITEM': 'අයිතමයක් එක් කරන්න',
        'CATEGORY': 'නිෂ්පාදනයේ නම',
        'PRODUCT_NAME': 'විස්තරය',
        'QTY': 'ප්‍රමාණය',
        'PRICE': 'මිල',
        'TOTAL': 'එකතුව',
        'SEARCH_CAT': 'නිෂ්පාදනය සොයන්න...',
        'ITEM_NAME': 'අයිතමයේ නම',
        'GRAND_TOTAL': 'මුළු එකතුව',
        'CANCEL': 'අවලංගු කරන්න',
        'PROCESSING': 'සැකසෙමින්...',
        'UPDATE_QUOTE': 'යාවත්කාලීන කරන්න',
        'CREATE_QUOTE_BTN': 'සාදන්න',
        'APPROVE_CONVERT_TITLE': 'අනුමත කර ඇණවුමක් බවට පත් කරන්න',
        'APPROVE_MSG_1': 'මෙය අනුමත කිරීමට ඔබට විශ්වාසද:',
        'APPROVE_MSG_2': 'මෙමගින් මෙය පාරිභෝගික ඇණවුමක් බවට පත් වී ඇණවුම් කළමනාකරණ පුවරුවට යොමු කෙරේ.',
        'YES_APPROVE': 'ඔව්, අනුමත කර පරිවර්තනය කරන්න',
        'CONFIRM_DELETE_TITLE': 'මකා දැමීම තහවුරු කරන්න',
        'DELETE_MSG_1': 'මෙම මිල ගණන් පත්‍රය මකා දැමීමට ඔබට විශ්වාසද?',
        'DELETE_MSG_2': 'මෙය ආපසු හැරවිය නොහැක.',
        'QUOTE_ID': 'හැඳුනුම්පත:',
        'YES_DELETE': 'ඔව්, මකා දමන්න'
      },
      'ADMIN_DASHBOARD': {
        'WELCOME': 'සචින්ත ටිම්බර් මෝල් වෙත සාදරයෙන් පිළිගනිමු',
        'SUBTITLE': 'ඔබේ දැව සහ ගෘහ භාණ්ඩ ඉන්වෙන්ටරි කාර්යක්ෂමව කළමනාකරණය කරන්න.',
        'USERS': 'පරිශීලකයින්',
        'USERS_DESC': 'කාර්ය මණ්ඩලය සහ භූමිකාවන්',
        'EMPLOYEES': 'සේවකයින්',
        'EMPLOYEES_DESC': 'සේවක වාර්තා සහ තත්වය',
        'SUPPLIERS': 'සැපයුම්කරුවන්',
        'SUPPLIERS_DESC': 'දායකයින් කළමනාකරණය',
        'CUSTOMERS': 'ගනුදෙනුකරුවන්',
        'CUSTOMERS_DESC': 'පාරිභෝගික නාමාවලිය',
        'SUPPLY': 'සැපයුම්',
        'SUPPLY_DESC': 'ද්‍රව්‍ය ඉල්ලීම්',
        'QUICK_ACTIONS': 'ඉක්මන් ක්‍රියා',
        'ADD_STAFF': 'නව කාර්ය මණ්ඩලයක් එක් කරන්න',
        'NEW_SUPPLY': 'නව සැපයුම් ඉල්ලීමක්',
        'CREATE_QUOTE': 'මිල ගණන් පත්‍රය සාදන්න',
        'CREATE_ORDER': 'ඇණවුමක් සාදන්න',
        'LOG_MGMT': 'ලොග් කළමනාකරණය',
        'MATERIAL_CUTTING': 'ද්‍රව්‍ය කැපීම',
        'RECORD_ATTENDANCE': 'පැමිණීම සටහන් කරන්න',
        'RUN_PAYROLL': 'වැටුප් ගෙවීම් ක්‍රියාත්මක කරන්න'
      },
      'EMPLOYEE_DASHBOARD': {
        'WELCOME': 'නැවත සාදරයෙන් පිළිගනිමු,',
        'SUBTITLE': 'සචින්ත ටිම්බර් මෝල් — සේවක මෙහෙයුම් ද්වාරය',
        'NO_PERMISSIONS_TITLE': 'අවසර ලබා දී නොමැත',
        'NO_PERMISSIONS_DESC1': 'ඔබේ පරිශීලක ගිණුමට දැනට පද්ධති මොඩියුල සඳහා ක්‍රියාකාරී අවසර කිසිවක් නොමැත.',
        'NO_PERMISSIONS_DESC2': 'අවශ්‍ය කාර්යයන් සඳහා ප්‍රවේශය ඉල්ලා සිටීමට කරුණාකර පරිපාලක අමතන්න.',
        'ACCESS_MODULE': 'මොඩියුලයට පිවිසෙන්න'
      },
      'SUPPLIER_DASHBOARD': {
        'WELCOME': 'නැවත සාදරයෙන් පිළිගනිමු,',
        'SUBTITLE': 'සචින්ත ටිම්බර් මෝල් — සැපයුම්කරු හවුල්කරු ද්වාරය',
        'WORKSPACE': 'සැපයුම්කරු වැඩබිම',
        'ACCESS_MODULE': 'මොඩියුලයට පිවිසෙන්න'
      },
      'EMPLOYEE_MANAGEMENT': {
        'TITLE': 'සේවක කළමනාකරණය',
        'SUBTITLE': 'කාර්ය මණ්ඩල වාර්තා සහ තනතුරු පවත්වා ගන්න',
        'ADD_NEW': 'නව සේවකයෙකු එක් කරන්න',
        'TOTAL_WORKFORCE': 'මුළු සේවක සංඛ්‍යාව',
        'ACTIVE_STAFF': 'ක්‍රියාකාරී කාර්ය මණ්ඩලය',
        'ON_LEAVE_INACTIVE': 'නිවාඩු/අක්‍රිය',
        'ID': '#හැඳුනුම්පත',
        'EMP_INFO': 'සේවක තොරතුරු',
        'NIC': 'ජා.හැ.අ.',
        'DESIGNATION': 'තනතුර',
        'MOBILE': 'ජංගම දුරකථන අංකය',
        'JOINED_DATE': 'සම්බන්ධ වූ දිනය',
        'STATUS': 'තත්වය',
        'ACTIONS': 'ක්‍රියා',
        'ACTIVE': 'ක්‍රියාකාරී',
        'INACTIVE': 'අක්‍රිය',
        'EDIT_DETAILS': 'විස්තර සංස්කරණය',
        'DEACTIVATE': 'අක්‍රිය කරන්න',
        'ACTIVATE': 'සක්‍රිය කරන්න',
        'DELETE_RECORD': 'වාර්තාව මකා දමන්න',
        'EDIT_TITLE': 'සේවක විස්තර සංස්කරණය',
        'EMP_NAME': 'සේවක නාමය',
        'EMAIL': 'විද්‍යුත් තැපැල් ලිපිනය',
        'ADDRESS': 'ලිපිනය',
        'CANCEL': 'අවලංගු කරන්න',
        'SAVE_CHANGES': 'වෙනස්කම් සුරකින්න'
      },
      'SUPPLIER_MANAGEMENT': {
        'TITLE': 'සැපයුම්කරු කළමනාකරණය',
        'SUBTITLE': 'දැව සහ ද්‍රව්‍ය සැපයුම්කරුවන් කළමනාකරණය කරන්න',
        'ADD_NEW': 'නව සැපයුම්කරුවෙකු එක් කරන්න',
        'TOTAL_SUPPLIERS': 'මුළු සැපයුම්කරුවන්',
        'ACTIVE_CONTRIBUTORS': 'ක්‍රියාකාරී දායකයින්',
        'INACTIVE_PAUSED': 'අක්‍රිය/නතර කළ',
        'ID': '#හැඳුනුම්පත',
        'SUPP_INFO': 'සැපයුම්කරු තොරතුරු',
        'CATEGORY': 'කාණ්ඩය',
        'CONTACT_INFO': 'සම්බන්ධතා තොරතුරු',
        'CREATED_DATE': 'නිර්මාණය කළ දිනය',
        'STATUS': 'තත්වය',
        'ACTIONS': 'ක්‍රියා',
        'ACTIVE': 'ක්‍රියාකාරී',
        'INACTIVE': 'අක්‍රිය',
        'EDIT_DETAILS': 'විස්තර සංස්කරණය',
        'DEACTIVATE': 'අක්‍රිය කරන්න',
        'ACTIVATE': 'සක්‍රිය කරන්න',
        'DELETE_RECORD': 'වාර්තාව මකා දමන්න',
        'NO_SUPPLIERS': 'සැපයුම්කරුවන් හමු නොවීය.',
        'EDIT_TITLE': 'සැපයුම්කරු විස්තර සංස්කරණය',
        'SUPP_NAME': 'සැපයුම්කරු නාමය',
        'MOBILE': 'ජංගම දුරකථන අංකය',
        'EMAIL': 'විද්‍යුත් තැපෑල',
        'ADDRESS': 'ලිපිනය',
        'CANCEL': 'අවලංගු කරන්න',
        'SAVE_CHANGES': 'වෙනස්කම් සුරකින්න'
      },
      'ATTENDANCE_MANAGEMENT': {
        'TITLE': 'සේවක පැමිණීම',
        'SUBTITLE': 'දෛනික පැමිණීම සහ වැඩ කරන පැය වාර්තා කර නිරීක්ෂණය කරන්න',
        'BULK_ACTION': 'සමූහ ක්‍රියාව',
        'ADD_RECORD': 'වාර්තාවක් එක් කරන්න',
        'SEARCH_DATE': 'දිනය අනුව සොයන්න',
        'FILTER_EMPLOYEE': 'සේවකයා අනුව පෙරහන් කරන්න',
        'ALL_EMPLOYEES': 'සියලුම සේවකයින්',
        'FILTER_RECORDS': 'වාර්තා පෙරහන් කරන්න',
        'EMP_DETAILS': 'සේවක විස්තර',
        'ATTENDANCE_DATE': 'පැමිණි දිනය',
        'STATUS': 'තත්වය',
        'CHECK_IN_OUT': 'ඇතුළු වීම / පිටවීම',
        'OVERTIME': 'අතිකාල',
        'REMARKS': 'සටහන්',
        'ACTIONS': 'ක්‍රියා',
        'NOT_RECORDED': 'වාර්තා කර නොමැත',
        'EDIT_RECORD': 'වාර්තාව සංස්කරණය කරන්න',
        'MONTHLY_SUMMARY': 'මාසික සාරාංශය',
        'DELETE_RECORD': 'වාර්තාව මකා දමන්න',
        'NO_LOGS': 'පැමිණීමේ ලොග් නොමැත',
        'NO_LOGS_DESC': 'ඔබගේ වත්මන් පෙරහන් නිර්ණායකවලට ගැලපෙන වාර්තා කිසිවක් හමු නොවීය.',
        'CLEAR_FILTERS': 'සියලුම පෙරහන් ඉවත් කරන්න',
        'EDIT_ATTENDANCE': 'පැමිණීම සංස්කරණය කරන්න',
        'MARK_ATTENDANCE': 'පැමිණීම සලකුණු කරන්න',
        'SELECT_EMPLOYEE': 'සේවකයෙකු තෝරන්න',
        'EMPLOYEE': 'සේවකයා',
        'ATTENDANCE_STATUS': 'පැමිණීමේ තත්වය',
        'CHECK_IN_TIME': 'ඇතුළු වූ වේලාව',
        'CHECK_OUT_TIME': 'පිට වූ වේලාව',
        'REMARKS_NOTES': 'සටහන්',
        'WARNING_MSG': 'මෙම දිනය සඳහා වාර්තාවක් දැනටමත් පවතී. සුරැකීම එය යාවත්කාලීන කරනු ඇත.',
        'SWITCH_EDIT': 'සංස්කරණයට මාරු වන්න',
        'CANCEL': 'අවලංගු කරන්න',
        'UPDATE_RECORD': 'වාර්තාව යාවත්කාලීන කරන්න',
        'SAVE_ATTENDANCE': 'පැමිණීම සුරකින්න',
        'ANALYTICS': 'පැමිණීමේ විශ්ලේෂණ',
        'ANALYSIS_MONTH': 'විශ්ලේෂණ මාසය',
        'ANALYSIS_YEAR': 'විශ්ලේෂණ වර්ෂය',
        'PRESENT': 'පැමිණි',
        'ABSENT': 'නොපැමිණි',
        'HALF_DAY': 'අර්ධ දිනය',
        'LEAVE': 'නිවාඩු',
        'HOLIDAYS': 'නිවාඩු දින',
        'WEEKENDS': 'සති අන්ත',
        'TOTAL_OT_HRS': 'මුළු අතිකාල පැය',
        'TOTAL_WORKING_DAYS': 'මුළු වැඩකරන දින',
        'GENERATING_REPORT': 'වාර්තාව ජනනය කරමින් පවතී...',
        'CLOSE_REPORT': 'වාර්තාව වසන්න',
        'BULK_ENTRY': 'සමූහ පැමිණීමේ ඇතුළත් කිරීම',
        'ACTIVE_EMPLOYEES_BADGE': 'ක්‍රියාකාරී සේවකයින්',
        'IN': 'ඇතුළු',
        'OUT': 'පිට',
        'SUBMIT_ALL': 'සියලුම වාර්තා යොමු කරන්න'
      },
      'LOAN_ADVANCE': {
        'TITLE': 'ණය සහ අත්තිකාරම් කළමනාකරණය',
        'SUBTITLE': 'සේවක ණය, අත්තිකාරම් සහ අයකර ගැනීමේ නීති නිරීක්ෂණය කරන්න',
        'REFRESH_DATA': 'දත්ත යාවත්කාලීන කරන්න',
        'TOTAL_ACTIVE_LOANS': 'මුළු සක්‍රිය ණය',
        'EXPECTED_COLLECTION': 'අපේක්ෂිත එකතුව (මාසික)',
        'PENDING_REQUESTS': 'පොරොත්තු ඉල්ලීම්',
        'ISSUE_NEW': 'නව ණය / අත්තිකාරම් නිකුත් කරන්න',
        'SELECT_EMPLOYEE': 'සේවකයෙකු තෝරන්න',
        'SELECT_EMP_OPTION': '-- සේවකයෙකු තෝරන්න --',
        'TYPE': 'වර්ගය',
        'LOAN': 'ණය',
        'ADVANCE': 'අත්තිකාරම්',
        'AMOUNT': 'මුදල (රු.)',
        'INSTALLMENTS': 'වාරික (මාස)',
        'MONTHLY_DEDUCTION': 'මාසික අඩු කිරීම',
        'REASON': 'හේතුව / අරමුණ',
        'ACTIVE_BALANCE_WARNING': 'සක්‍රිය ශේෂය:',
        'PROCESSING': 'සැකසෙමින් පවතී...',
        'APPLY_LOAN': 'ණය අයදුම් කර නීතිය සකසන්න',
        'LOAN_HISTORY': 'ණය ඉතිහාසය සහ නිරීක්ෂණය',
        'EMPLOYEE': 'සේවකයා',
        'AMOUNT_TH': 'මුදල',
        'PROGRESS': 'ප්‍රගතිය',
        'STATUS': 'තත්වය',
        'BAL': 'ශේෂය:',
        'NO_RECORDS': 'වාර්තා හමු නොවීය.'
      },
      'PAYROLL_MANAGEMENT': {
        'TITLE': 'වැටුප් ගෙවීම් සහ ස්වයංක්‍රීයකරණය',
        'SUBTITLE': 'මාසික සේවක ගෙවීම් උත්පාදනය කරන්න, පෙරදසුන් කරන්න සහ තහවුරු කරන්න',
        'PARAMETERS': 'වැටුප් ගෙවීම් පරාමිතීන්',
        'SELECT_EMPLOYEE': 'සේවකයෙකු තෝරන්න',
        'CHOOSE_EMP': '-- සේවකයෙකු තෝරන්න --',
        'MONTH': 'මාසය',
        'YEAR': 'වර්ෂය',
        'PAYMENT_FREQ': 'ගෙවීම් වාර ගණන',
        'MONTHLY': 'මාසික',
        'DAILY_WAGE': 'දෛනික වැටුප',
        'DEDUCT_LOAN': 'ණය වාරිකය අඩු කරන්න',
        'OTHER_DEDUCTIONS': 'වෙනත් අඩු කිරීම් (රු.)',
        'DEDUCTION_REASON': 'අඩු කිරීමට හේතුව',
        'LOAN_OVERRIDE': 'ණය වෙනස් කිරීම (විකල්ප)',
        'LOAN_OVERRIDE_HINT': 'ස්වයංක්‍රීයව ගණනය කළ වාරිකයට වඩා වැඩි අගයන් පමණක් පිළිගනු ලැබේ.',
        'CALCULATING': 'ගණනය කරමින් පවතී...',
        'PREVIEW_PAYROLL': 'වැටුප් ගෙවීම් පෙරදසුන',
        'PREVIEW_TITLE': 'වැටුප් ගෙවීම් පෙරදසුන:',
        'EARNINGS_BREAKDOWN': 'ආදායම් බිඳවැටීම',
        'BASIC_SALARY': 'මූලික වැටුප',
        'OVERTIME': 'අතිකාල',
        'GROSS_EARNINGS': 'දළ ආදායම',
        'DEDUCTIONS_ADJ': 'අඩු කිරීම් සහ ගැලපීම්',
        'LOAN_RECOVERY': 'ණය අයකර ගැනීම',
        'OTHER_DEDUCT_LBL': 'වෙනත් අඩු කිරීම්',
        'DAILY_WAGES_PAID': 'දැනටමත් ගෙවා ඇති දෛනික වැටුප්',
        'NET_PAYABLE': 'ශුද්ධ ගෙවිය යුතු මුදල: රු.',
        'DISBURSE_DESC': 'සඳහා බෙදා හැරීමට නියමිත මුළු මුදල',
        'ATTENDANCE_FLAGS': 'පැමිණීමේ සලකුණු:',
        'CANCEL': 'අවලංගු කරන්න',
        'FINALIZING': 'අවසන් කරමින් පවතී...',
        'CONFIRM_GENERATE': 'තහවුරු කර වියදම ජනනය කරන්න',
        'NO_PREVIEW': 'පෙරදසුනක් ජනනය කර නොමැත',
        'NO_PREVIEW_DESC': 'ගණනය කිරීමේ විස්තර බැලීමට සේවකයෙකු සහ කාල සීමාවක් තෝරා "වැටුප් ගෙවීම් පෙරදසුන" ක්ලික් කරන්න.'
      },
      'DESIGNATION_SALARY': {
        'TITLE': 'තනතුරු වැටුප් කළමනාකරණය',
        'SUBTITLE': 'සමාගමේ විවිධ භූමිකාවන් සඳහා මූලික වැටුප් අනුපාත සකසන්න',
        'EDIT_MAPPING': 'සිතියම්ගත කිරීම සංස්කරණය කරන්න',
        'ADD_NEW': 'නව තනතුරක් එක් කරන්න',
        'DESIG_NAME': 'තනතුරේ නම',
        'BASIC_RATE': 'මූලික වැටුප / අනුපාතය (රු.)',
        'RATE_TYPE': 'අනුපාත වර්ගය',
        'DAILY_RATE': 'දෛනික අනුපාතය',
        'MONTHLY_FIXED': 'මාසික (ස්ථාවර)',
        'IS_ACTIVE': 'සක්‍රියයි',
        'UPDATE_RATE': 'අනුපාතය යාවත්කාලීන කරන්න',
        'SAVE_RATE': 'අනුපාතය සුරකින්න',
        'CANCEL': 'අවලංගු කරන්න',
        'DESIGNATION': 'තනතුර',
        'RATE_RS': 'අනුපාතය (රු.)',
        'TYPE': 'වර්ගය',
        'STATUS': 'තත්වය',
        'ACTIONS': 'ක්‍රියා',
        'ACTIVE': 'ක්‍රියාකාරී',
        'INACTIVE': 'අක්‍රිය',
        'NO_DESIGNATIONS': 'තනතුරු හමු නොවීය. ඔබේ පළමු එක වම් පසින් එක් කරන්න.'
      },
      'SUPPLY_REQUEST_MANAGEMENT': {
        'TITLE': 'අමුද්‍රව්‍ය සැපයුම් ඉල්ලීම්',
        'SUBTITLE': 'සැපයුම්කරුවන්ගේ ඉල්ලීම් කළමනාකරණය කර ඒවා ඉන්වෙන්ටරි සැපයුම් ඇණවුම් බවට පරිවර්තනය කරන්න',
        'SEARCH_PLACEHOLDER': 'සැපයුම්කරු හෝ හැඳුනුම්පත මගින් සොයන්න...',
        'ALL_STATUS': 'සියලුම තත්වයන්',
        'PENDING': 'පොරොත්තු',
        'APPROVED': 'අනුමත කර ඇත',
        'PARTIALLY_APPROVED': 'අර්ධ වශයෙන් අනුමත කර ඇත',
        'REJECTED': 'ප්‍රතික්ෂේප කරන ලදි',
        'CONVERTED': 'පරිවර්තනය කර ඇත',
        'NEW_REQUEST': 'නව ඉල්ලීම',
        'TOTAL_REQUESTS': 'මුළු ඉල්ලීම්',
        'REQUEST_LIST': 'සැපයුම් ඉල්ලීම් ලැයිස්තුව',
        'RECORDS': 'වාර්තා',
        'LOADING': 'ඉල්ලීම් පූරණය වෙමින් පවතී...',
        'SUPPLIER': 'සැපයුම්කරු',
        'REQUEST_DATE': 'ඉල්ලුම් කළ දිනය',
        'MATERIALS': 'ද්‍රව්‍ය',
        'STATUS': 'තත්වය',
        'ACTIONS': 'ක්‍රියා',
        'NO_REQUESTS': 'ඉල්ලීම් හමු නොවීය',
        'SHOWING': 'පෙන්වන්නේ',
        'OF': '-',
        'PAGE': 'පිටුව',
        'CREATE_TITLE': 'නව සැපයුම් ඉල්ලීමක් සාදන්න',
        'SELECT_SUPPLIER': 'සැපයුම්කරු තෝරන්න',
        'TRANSPORT_SUPPLIER': 'සැපයුම්කරු මගින් ප්‍රවාහනය',
        'TRANSPORT_NOTES': 'ප්‍රවාහන සටහන්',
        'REMARKS': 'සටහන්',
        'REQUESTED_MATERIALS': 'ඉල්ලුම් කළ ද්‍රව්‍ය',
        'ADD_MATERIAL': 'ද්‍රව්‍ය එක් කරන්න',
        'MATERIAL': 'ද්‍රව්‍ය',
        'REQUESTED_CFT': 'ඉල්ලුම් කළ CFT',
        'CANCEL': 'අවලංගු කරන්න',
        'SEND_REQUEST': 'ඉල්ලීම යවන්න',
        'REVIEW_REQUEST': 'ඉල්ලීම සමාලෝචනය කරන්න',
        'DATE': 'දිනය',
        'TRANSPORT': 'ප්‍රවාහනය',
        'APPROVE_QUANTITIES': 'ප්‍රමාණ අනුමත කර මිල නියම කරන්න',
        'APPROVED_CFT': 'අනුමත CFT',
        'UNIT_PRICE': 'ඒකක මිල (රු.)',
        'TOTAL_EST': 'මුළු මුදල (ඇස්තමේන්තුගත)',
        'REJECT': 'ප්‍රතික්ෂේප කරන්න',
        'APPROVE_REQ': 'ඉල්ලීම අනුමත කරන්න',
        'CLOSE': 'වසන්න',
        'CONVERT_TITLE': 'සැපයුම් ඇණවුමකට (GRN) පරිවර්තනය කරන්න',
        'CONVERTING': 'ඉල්ලීම පරිවර්තනය වෙමින් පවතී',
        'FROM': 'වෙතින්',
        'TARGET_VOLUME': 'ඉලක්ක පරිමාව (සැපයුම්කරු විසින් අනුමත කරන ලද):',
        'INVOICE_NUMBER': 'ඉන්වොයිස් අංකය',
        'SUPPLY_DATE': 'සැපයුම් දිනය',
        'TRANSPORT_COST': 'ප්‍රවාහන ගාස්තුව (රු.)',
        'CUTTING_FEE': 'කැපීමේ ගාස්තුව (රු.)',
        'CUTTING_FEE_EMP': 'කැපීමේ ගාස්තු ලබන සේවකයා',
        'SELECT_EMP': 'සේවකයෙකු තෝරන්න',
        'ACTUAL_LOG_DETAILS': 'සත්‍ය දැව කොට විස්තර',
        'ADD': 'එක් කරන්න',
        'LOG_NO': 'දැව කොට #',
        'LENGTH': 'දිග (අඟල්)',
        'GIRTH': 'වටප්‍රමාණය (අඟල්)',
        'SUPPLIER_PRICE': 'සැපයුම්කරු (රු.)',
        'API_PRICE': 'API මිල (රු.)',
        'NEGOTIATED': 'සාකච්ඡා කළ (රු.)',
        'CFT': 'CFT',
        'TOTAL': 'මුළු මුදල',
        'GRAND_SUMMARY': 'මහා සාරාංශය',
        'TARGET': 'ඉලක්කය:',
        'REJECT_REQ': 'ඉල්ලීම ප්‍රතික්ෂේප කරන්න',
        'COMPLETE_ORDER': 'ඇණවුම සම්පූර්ණ කර GRN ජනනය කරන්න'
      },
      'SUPPLY_RAW_MATERIAL': {
        'TITLE': 'සැපයුම්කරු ඇණවුමක් එක් කරන්න',
        'SUBTITLE': 'අමුද්‍රව්‍ය සැපයුම් දැව කොට වාර්තා කර අමතර ගාස්තු නිරීක්ෂණය කරන්න',
        'SUPPLIER': 'සැපයුම්කරු',
        'SELECT_SUPPLIER': 'සැපයුම්කරු තෝරන්න',
        'INVOICE_NUMBER': 'ඉන්වොයිස් අංකය',
        'AUTO_GEN': 'සුරැකීමේදී ස්වයංක්‍රීයව ජනනය වේ',
        'WOOD_TYPE': 'දැව වර්ගය',
        'LOG_NUMBER': 'දැව කොට අංකය',
        'LENGTH': 'දිග (අඟල්)',
        'GIRTH': 'වටප්‍රමාණය (අඟල්)',
        'QTY_CFT': 'ප්‍රමාණය (CFT)',
        'PRICE_CFT': 'මිල/CFT',
        'LINE_TOTAL': 'පේළියේ මුළු මුදල',
        'ADD_LOG_ROW': 'තවත් දැව කොට පේළියක් එක් කරන්න',
        'FEES_DEDUCTIONS': 'අමතර ගාස්තු සහ අඩු කිරීම්',
        'TRANSPORT_CHARGES': 'ප්‍රවාහන ගාස්තු',
        'CUTTING_FEE': 'කැපීමේ ගාස්තුව',
        'CUTTING_EMPLOYEE': 'කැපීමේ ගාස්තු ලබන සේවකයා',
        'SELECT_EMP': 'සේවකයෙකු තෝරන්න',
        'TREE_SELLER_NOTE': 'සටහන: ගස් විකුණන්නන් සඳහා මෙම අඩු කිරීම් සාමාන්‍යයෙන් දළ මුළු මුදලින් අඩු කරනු ලැබේ.',
        'GROSS_TOTAL': 'දළ මුළු මුදල',
        'TOTAL_DEDUCTIONS': 'මුළු අඩු කිරීම්',
        'NET_PAYABLE': 'ශුද්ධ ගෙවිය යුතු මුදල',
        'RECORDING': 'සැපයුම වාර්තා කරමින් පවතී...',
        'CONFIRM_GENERATE': 'තහවුරු කර GRN ජනනය කරන්න'
      },
      'RAW_MATERIAL_CUTTING': {
        'TITLE': 'අමුද්‍රව්‍ය කැපීමේ ක්‍රියාවලිය',
        'SUBTITLE': 'පරිමා දෘශ්‍යමාන කිරීමට සහ කැපීමේ ප්‍රතිදානය වාර්තා කිරීමට දැව කොට තෝරන්න',
        'SEARCH': 'ඉන්වොයිසිය හෝ දැව කොට # මගින් සොයන්න...',
        'SELECT': 'තෝරන්න',
        'INVOICE_NO': 'ඉන්වොයිස් #',
        'LOG_NO': 'දැව කොට #',
        'LENGTH': 'දිග (අඟල්)',
        'GIRTH': 'වටප්‍රමාණය (අඟල්)',
        'VOLUME': 'පරිමාව (CFT)',
        'NO_LOGS': 'ගැලපෙන අමුද්‍රව්‍ය හමු නොවීය.',
        'VISUALIZER': 'සිලින්ඩරාකාර දැව කොට දෘශ්‍යමානකරණය',
        'INVOICE_REF': 'ඉන්වොයිස් යොමුව',
        'TOTAL_VOLUME': 'මුළු පරිමාව',
        'FORMULA': 'Hopper ගේ නීතිය මගින් ගණනය කර ඇත: (වටප්‍රමාණය² × දිග) / 12',
        'SELECT_ONE': 'එහි මානයන් දෘශ්‍යමාන කිරීමට හරියටම එක් දැව කොට පේළියක් තෝරන්න',
        'GENERATED_PRODUCTS': 'ජනනය කළ නිෂ්පාදන',
        'SPECIFY_PRODUCTS': 'කැපීමෙන් පසු ලබාගත් වර්ග සහ ප්‍රමාණ සඳහන් කරන්න',
        'ADD_ROW': 'තවත් පේළියක් එක් කරන්න',
        'PRODUCT_CAT': 'නිෂ්පාදන කාණ්ඩය',
        'CHOOSE_CAT': 'කාණ්ඩය තෝරන්න...',
        'QTY_PRODUCED': 'නිෂ්පාදනය කළ ප්‍රමාණය',
        'LOGS_SELECTED': 'සැකසීම සඳහා දැව කොට තෝරා ඇත',
        'CLEAR_ALL': 'සියල්ල ඉවත් කරන්න',
        'PROCESS_CUTTING': 'කැපීම සකසන්න',
        'PROCESSING': 'සැකසෙමින් පවතී...'
      },
      'EXPENSE_MANAGEMENT': {
        'TITLE': 'වියදම් ගිණුම් කළමනාකරණය',
        'SUBTITLE': 'ආයතනික වියදම් සහ සැපයුම්කරු ඉන්වොයිස් ලුහුබැඳීම, කළමනාකරණය කිරීම සහ විගණනය කිරීම',
        'EXPENSE_DETAILS': 'වියදම් විස්තර',
        'DESCRIPTION': 'විස්තරය:',
        'DATE': 'දිනය:',
        'AMOUNT': 'මුදල:',
        'CATEGORY': 'කාණ්ඩය:',
        'RECIPIENT': 'ලබන්නා:',
        'GRN': 'GRN:',
        'REMARKS': 'සටහන්:',
        'EXPENSE_ID': 'වියදම් හැඳුනුම්පත:',
        'USER_ID': 'පරිශීලක හැඳුනුම්පත:',
        'REFRESH_DATA': 'දත්ත යාවත්කාලීන කරන්න',
        'TOTAL_EXPENDITURE': 'මුළු වියදම',
        'ACTIVE_CATEGORIES': 'සක්‍රිය වියදම් කාණ්ඩ',
        'MTD_COST': 'මෙම මාසයේ මේ දක්වා වියදම',
        'RECORD_NEW': 'නව වියදමක් වාර්තා කරන්න',
        'MODIFY_ENTRY': 'වියදම් ප්‍රවේශය වෙනස් කරන්න #',
        'UPDATE_DETAILS': 'ගනුදෙනු විස්තර යාවත්කාලීන කරන්න',
        'ENTER_NEW': 'නව ව්‍යාපාරික වියදම් අයිතමයක් ඇතුළත් කරන්න',
        'COST_CATEGORY': 'වියදම් කාණ්ඩය',
        'CHOOSE_CATEGORY': '-- කාණ්ඩය තෝරන්න --',
        'AMOUNT_LKR': 'මුදල (රු.)',
        'DATE_LABEL': 'දිනය',
        'PAID_TO': 'ගෙවූයේ කාහටද / ලබන්නා',
        'PAID_TO_PLACEHOLDER': 'සැපයුම්කරු, සේවකයා හෝ විකුණුම්කරුගේ නම',
        'DESC_LABEL': 'විස්තරය',
        'DESC_PLACEHOLDER': 'මෙම වියදම කුමක් සඳහාද?',
        'ASSOC_GRN': 'ආශ්‍රිත GRN (විකල්ප)',
        'NOT_ASSOC_GRN': '-- GRN සමග සම්බන්ධ නොවේ --',
        'AUDIT_REMARKS': 'විගණන සටහන් (විකල්ප)',
        'AUDIT_PLACEHOLDER': 'විකල්ප විගණන හෝ ලුහුබැඳීමේ සටහන්',
        'SAVING': 'සුරකිමින් පවතී...',
        'UPDATE_TRANS': 'ගනුදෙනුව යාවත්කාලීන කරන්න',
        'RECORD_TRANS': 'ගනුදෙනුව වාර්තා කරන්න',
        'CANCEL': 'අවලංගු කරන්න',
        'AUDIT_LOGS': 'වියදම් විගණන ලොග්',
        'AUDIT_SUBTITLE': 'වාර්තා කර ඇති ගනුදෙනු සොයන්න සහ විගණනය කරන්න',
        'FILTER_EXPENSES': 'වියදම් පෙරහන් කරන්න...',
        'SORT': 'වර්ග කිරීම:',
        'LATEST_FIRST': 'නවීනතම පළමුව',
        'OLDEST_FIRST': 'පැරණිතම පළමුව',
        'TRANSACTION': 'ගනුදෙනුව',
        'RECIPIENT_TH': 'ලබන්නා',
        'CATEGORY_TH': 'කාණ්ඩය',
        'AMOUNT_TH': 'මුදල',
        'ACTIONS': 'ක්‍රියා',
        'NOTES': 'සටහන්:',
        'NO_RECORDS': 'වියදම් වාර්තා හමු නොවීය.',
        'LOADING': 'දත්ත පූරණය වෙමින් පවතී...',
        'SHOWING': 'පෙන්වන්නේ',
        'OF': '-',
        'PREVIOUS': 'පෙර',
        'NEXT': 'මීළඟ',
        'PAGE': 'පිටුව'
      },
      'RECEIPT_MANAGEMENT': {
        'TITLE': 'රිසිට්පත් සහ ගෙවීම් ඉතිහාසය',
        'SUBTITLE': 'පාරිභෝගික ඉන්වොයිස් ගෙවීම් කළමනාකරණය සහ දර්ශනය කිරීම',
        'SEARCH_PLACEHOLDER': 'රිසිට්පත, පාරිභෝගිකයා, හෝ ඇණවුම සොයන්න...',
        'ADD_RECEIPT': 'රිසිට්පතක් එක් කරන්න',
        'TOTAL_REVENUE': 'ලැබුණු මුළු ආදායම',
        'TOTAL_RECEIPTS': 'ජනනය කළ මුළු රිසිට්පත්',
        'CASH_PAYMENTS': 'මුදල් ගෙවීම්',
        'SORT_ORDER': 'වර්ග කිරීමේ අනුපිළිවෙළ:',
        'LATEST_FIRST': 'නවීනතම පළමුව (පෙරනිමි)',
        'OLDEST_FIRST': 'පැරණිතම පළමුව',
        'RETRIEVING_DATA': 'ගෙවීම් දත්ත ලබාගනිමින් පවතී...',
        'NO_RECEIPTS': 'රිසිට්පත් වාර්තා කර නොමැත',
        'NO_RECEIPTS_DESC': 'ගැලපෙන රිසිට්පත් කිසිවක් හමු නොවීය. නව ගෙවීමක් වාර්තා කිරීමට "රිසිට්පතක් එක් කරන්න" ක්ලික් කරන්න.',
        'RECEIPT_NO': 'රිසිට්පත් අංකය',
        'DATE': 'දිනය',
        'CUSTOMER_NAME': 'පාරිභෝගික නම',
        'ORDER_NO': 'ඇණවුම් අංකය',
        'PAYMENT_MODE': 'ගෙවීම් ආකාරය',
        'TOTAL_AMOUNT': 'මුළු මුදල',
        'ACTIONS': 'ක්‍රියා',
        'ID': 'හැඳුනුම්පත:',
        'NA': 'අදාළ නොවේ',
        'SHOWING_PAGE': 'පෙන්වන පිටුව',
        'OF': 'සහ පිටු',
        'TOTAL_RECORDS': 'මුළු වාර්තා',
        'PREVIOUS': 'පෙර',
        'NEXT': 'මීළඟ',
        'PAGE': 'පිටුව'
      },
      'PRODUCT_CATEGORY': {
        'TITLE': 'නිෂ්පාදන කාණ්ඩ කළමනාකරණය',
        'SUBTITLE': 'විවිධ දැව/ගෘහභාණ්ඩ කාණ්ඩ එක් කරන්න සහ කළමනාකරණය කරන්න',
        'EDIT_CATEGORY': 'කාණ්ඩය සංස්කරණය කරන්න',
        'ADD_NEW': 'නව කාණ්ඩයක් එක් කරන්න',
        'MATERIAL_CATEGORY': 'ද්‍රව්‍ය කාණ්ඩය',
        'MATERIAL_PLACEHOLDER': 'උදා. තේක්ක ලී',
        'DESCRIPTION': 'විස්තරය',
        'DESC_PLACEHOLDER': 'කාණ්ඩයේ විස්තර...',
        'UNIT': 'මිනුම් ඒකකය',
        'PRICE': 'ඒකක මිල (රු.)',
        'UPDATE': 'කාණ්ඩය යාවත්කාලීන කරන්න',
        'CREATE': 'කාණ්ඩය සාදන්න',
        'CANCEL': 'අවලංගු කරන්න',
        'LIST_TITLE': 'කාණ්ඩ ලැයිස්තුව',
        'LIST_SUBTITLE': 'නිෂ්පාදන කාණ්ඩ සොයන්න සහ කළමනාකරණය කරන්න',
        'SEARCH': 'කාණ්ඩ සොයන්න...',
        'TH_CATEGORY': 'කාණ්ඩය',
        'TH_UNIT': 'ඒකකය',
        'TH_PRICE': 'මිල',
        'TH_ACTIONS': 'ක්‍රියා',
        'LOADING': 'කාණ්ඩ පූරණය වෙමින් පවතී...',
        'NO_CATEGORIES': 'ගැලපෙන කාණ්ඩ හමු නොවීය.',
        'NO_CATEGORIES_ADD': 'කාණ්ඩ හමු නොවීය. ඔබේ පළමු කාණ්ඩය එක් කරන්න!',
        'SHOWING': 'පෙන්වන්නේ',
        'OF': '-',
        'PREVIOUS': 'පෙර',
        'NEXT': 'මීළඟ',
        'PAGE': 'පිටුව'
      },
      'PRODUCT_STOCK': {
        'TITLE': 'තොග ඉන්වෙන්ටරි',
        'SUBTITLE': 'වත්මන් ද්‍රව්‍ය කාණ්ඩ සහ පවතින තොග පරිමාවන්හි තත්‍ය කාලීන දළ විශ්ලේෂණය',
        'REFRESH': 'යාවත්කාලීන කරන්න',
        'TH_STOCK_ID': 'තොග හැඳුනුම්පත',
        'TH_MATERIAL_CATEGORY': 'ද්‍රව්‍ය කාණ්ඩය',
        'TH_DESCRIPTION': 'විස්තරය',
        'TH_UNIT': 'මිනුම් ඒකකය',
        'TH_PRICE': 'ඒකක මිල',
        'TH_AVAILABLE_QTY': 'පවතින ප්‍රමාණය',
        'LOADING': 'පූරණය වෙමින් පවතී...',
        'NO_RECORDS': 'ඔබගේ සෙවුමට ගැළපෙන තොග වාර්තා හමු නොවීය.'
      },
      'SUPPLY_RAW_MATERIAL_DASHBOARD': {
        'TITLE': 'දැව කඳන් කළමනාකරණය',
        'SUBTITLE': 'වාර්තා කර ඇති සියලුම අමුද්‍රව්‍ය සැපයුම් ඇණවුම් බලන්න සහ කළමනාකරණය කරන්න',
        'SEARCH_PLACEHOLDER': 'සැපයුම්කරු හෝ ඉන්වොයිසිය මගින් සොයන්න...',
        'NEW_ORDER': 'නව සැපයුම් ඇණවුම',
        'TOTAL_ORDERS': 'මුළු සැපයුම් ඇණවුම්',
        'TOTAL_MATERIAL': 'මුළු ද්‍රව්‍ය (CFT)',
        'GROSS_EXPENDITURE': 'දළ වියදම',
        'LOADING': 'සැපයුම් වාර්තා පූරණය වෙමින් පවතී...',
        'TH_ID': 'හැඳුනුම්පත',
        'TH_INVOICE': 'ඉන්වොයිස් #',
        'TH_SUPPLIER': 'සැපයුම්කරු',
        'TH_DATE': 'දිනය',
        'TH_WOOD_TYPE': 'දැව වර්ගය',
        'TH_TOTAL_CFT': 'මුළු CFT',
        'TH_NET_AMOUNT': 'ශුද්ධ මුදල',
        'TH_GRN_STATUS': 'GRN තත්ත්වය',
        'TH_ACTIONS': 'ක්‍රියා',
        'GRN_CREATED': 'GRN සාදන ලදි',
        'PENDING': 'පොරොත්තු',
        'NO_RECORDS': 'තවමත් සැපයුම් ඇණවුම් වාර්තා කර නොමැත.',
        'SHOWING': 'පෙන්වන්නේ',
        'OF': '-',
        'PREVIOUS': 'පෙර',
        'NEXT': 'මීළඟ',
        'PAGE': 'පිටුව',
        'DETAILS_TITLE': 'සැපයුම් විස්තර',
        'INVOICE': 'ඉන්වොයිසිය:',
        'WOOD_TYPE_MAIN': 'දැව වර්ගය (ප්‍රධාන)',
        'LOG_BREAKDOWN': 'දැව කඳන් විස්තර බිඳවැටීම',
        'LOG_NO': 'කඳ #',
        'L_FT': 'L (අඟල්)',
        'G_IN': 'G (අඟල්)',
        'QTY_CFT': 'ප්‍රමාණය (CFT)',
        'PRICE_CFT': 'මිල (CFT සඳහා)',
        'LINE_TOTAL': 'රේඛා එකතුව',
        'TOTAL_MATERIAL_VOL': 'මුළු ද්‍රව්‍ය පරිමාව',
        'CLOSE': 'වසන්න',
        'VIEW_GRN': 'GRN ඉන්වොයිසිය බලන්න'
      },

      'USER_MANAGEMENT_DASHBOARD': {
        'TITLE': 'පරිශීලක කළමනාකරණය',
        'SUBTITLE': 'පද්ධති පරිශීලකයින්, භූමිකාවන් සහ ප්‍රවේශ තත්ත්වය කළමනාකරණය කරන්න',
        'ADD_NEW_USER': 'නව පරිශීලකයෙකු එක් කරන්න',
        'SYSTEM_USERS': 'පද්ධති පරිශීලකයින්',
        'ACTIVE_ACCESS': 'සක්‍රිය ප්‍රවේශය',
        'RESTRICTED': 'සීමා කර ඇත/අක්‍රිය කර ඇත',
        'TH_ID': '#හැඳුනුම්පත',
        'TH_USER_INFO': 'පරිශීලක තොරතුරු',
        'TH_NIC': 'ජා.හැ.ප.',
        'TH_ROLE': 'භූමිකාව',
        'TH_STATUS': 'තත්ත්වය',
        'TH_LAST_LOGIN': 'අවසන් පිවිසුම',
        'TH_ACTIONS': 'ක්‍රියා',
        'ROLE_ADMIN': 'පරිපාලක',
        'ROLE_EMPLOYEE': 'සේවකයා',
        'ACTIVE': 'සක්‍රිය',
        'INACTIVE': 'අක්‍රිය',
        'NEVER': 'කවදාවත් නැත',
        'CANCEL': 'අවලංගු කරන්න',
        'CONFIRM': 'තහවුරු කරන්න',
        'MANAGE_PRIVILEGES': 'සේවක වරප්‍රසාද කළමනාකරණය',
        'CONFIGURE_ACCESS': 'කාර්යයන් සඳහා ප්‍රවේශය වින්‍යාස කරන්න',
        'SAVE_CHANGES': 'වෙනස්කම් සුරකින්න'
      },

      'DASHBOARD_CARDS': {
        'EMPLOYEES': 'සේවකයින්',
        'EMPLOYEES_DESC': 'සේවක විස්තර, පැතිකඩ සහ තනතුරු කළමනාකරණය කරන්න.',
        'ATTENDANCE': 'පැමිණීම',
        'ATTENDANCE_DESC': 'සේවක දෛනික පැමිණීම වාර්තා කිරීම සහ නිරීක්ෂණය කිරීම.',
        'LOANS': 'ණය සහ අත්තිකාරම්',
        'LOANS_DESC': 'සේවක ණය සහ අත්තිකාරම් අනුමත කිරීම සහ නිරීක්ෂණය කිරීම.',
        'PAYROLL': 'වැටුප් ස්වයංක්‍රීයකරණය',
        'PAYROLL_DESC': 'වැටුප්, පඩි සැකසීම සහ වැටුප් පත්‍රිකා ජනනය කිරීම.',
        'DESIGNATION': 'තනතුරු අනුපාත',
        'DESIGNATION_DESC': 'විවිධ තනතුරු සඳහා වැටුප් අනුපාත සකසන්න.',
        
        'SUPPLIERS': 'සැපයුම්කරුවන්',
        'SUPPLIERS_DESC': 'අමුද්‍රව්‍ය සැපයුම්කරුවන් ලියාපදිංචි කිරීම සහ කළමනාකරණය කිරීම.',
        'SUPPLY_REQUESTS': 'සැපයුම් ඉල්ලීම්',
        'SUPPLY_REQUESTS_DESC_EMP': 'දැව සැපයුම් ඉල්ලීම් නිර්මාණය කිරීම සහ නිරීක්ෂණය කිරීම.',
        'SUPPLY_REQUESTS_DESC_SUP': 'දැව ඉල්ලීම් සමාලෝචනය කරන්න, ලබා ගත හැකි බව තහවුරු කරන්න, සහ සැපයුම් පරිමාවන් අනුමත කරන්න.',
        'LOG_MGMT': 'දැව කඳන් කළමනාකරණය',
        'LOG_MGMT_DESC': 'දැව කඳන් සැපයුම, දැව පරිමාව සහ තොගය නිරීක්ෂණය කරන්න.',
        'MATERIAL_CUTTING': 'ද්‍රව්‍ය කැපීම',
        'MATERIAL_CUTTING_DESC': 'දැව කැපීම සහ ප්‍රතිදාන තොගය සකසන්න.',
        
        'CUSTOMERS': 'පාරිභෝගිකයින්',
        'CUSTOMERS_DESC': 'ගනුදෙනුකරුවන්ගේ වාර්තා සහ විස්තර කළමනාකරණය කරන්න.',
        'QUOTATIONS': 'මිල කැඳවීම්',
        'QUOTATIONS_DESC': 'ගනුදෙනුකරුවන් සඳහා මිල කැඳවීම් නිර්මාණය කිරීම සහ යැවීම.',
        'ORDERS': 'ඇණවුම්',
        'ORDERS_DESC': 'ගෘහ භාණ්ඩ නිෂ්පාදන ඇණවුම් කළමනාකරණය කරන්න.',
        'RECEIPTS': 'රිසිට්පත්',
        'RECEIPTS_DESC': 'පාරිභෝගික රිසිට්පත් සහ ලැබෙන ගෙවීම් කළමනාකරණය කරන්න.',
        
        'EXPENSES': 'වියදම්',
        'EXPENSES_DESC': 'නිෂ්පාදන, මෙහෙයුම් සහ සාමාන්‍ය වියදම් නිරීක්ෂණය කරන්න.',
        'PRODUCT_CATEGORY': 'නිෂ්පාදන කාණ්ඩය',
        'PRODUCT_CATEGORY_DESC': 'ගෘහ භාණ්ඩ කාණ්ඩ සහ දැව වර්ග කළමනාකරණය කරන්න.',

        'MY_SUPPLIES': 'මගේ සැපයුම්',
        'MY_SUPPLIES_DESC': 'ඔබගේ සැපයුම්කරු ගිණුම යටතේ වාර්තා කර ඇති අමුද්‍රව්‍ය සැපයුම් ඇණවුම් බලන්න.',
        'PROFILE': 'පැතිකඩ',
        'PROFILE_DESC': 'ඔබගේ සැපයුම්කරු ගිණුම, සම්බන්ධතා සහ ව්‍යාපාරික විස්තර යාවත්කාලීනව තබා ගන්න.',

        'CAT_USER_MGMT': 'පරිශීලක කළමනාකරණය',
        'CAT_SUPPLY_CHAIN': 'සැපයුම් දාමය',
        'CAT_SALES_CUSTOMERS': 'විකුණුම් සහ පාරිභෝගිකයින්',
        'CAT_FINANCIALS': 'මූල්‍ය',
        'CAT_INVENTORY': 'ඉන්වෙන්ටරි'
      }
    }
  };

  constructor() {
    if (typeof localStorage !== 'undefined') {
      const savedLang = localStorage.getItem('selectedLang');
      if (savedLang) {
        this.currentLang.next(savedLang);
      }
    }
  }

  setLanguage(lang: string) {
    this.currentLang.next(lang);
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('selectedLang', lang);
    }
  }

  getLanguage() {
    return this.currentLang.value;
  }

  translate(key: string): string {
    const lang = this.currentLang.value;
    const keys = key.split('.');
    let translation = this.translations[lang];
    
    for (const k of keys) {
      if (translation && translation[k]) {
        translation = translation[k];
      } else {
        // Fallback: check flat key in SIDEBAR, HEADER, or PAGE_TITLES first
        const sidebarTrans = this.translations[lang]?.['SIDEBAR']?.[key];
        if (sidebarTrans) return sidebarTrans;
        const headerTrans = this.translations[lang]?.['HEADER']?.[key];
        if (headerTrans) return headerTrans;
        const pageTitleTrans = this.translations[lang]?.['PAGE_TITLES']?.[key];
        if (pageTitleTrans) return pageTitleTrans;
        return key; // Return key if translation not found
      }
    }
    
    return translation;
  }
}
